namespace Battlehub.UIControls;

[Token(Token = "0x2000037")]
public class TreeViewItem : ItemContainer
{
	[CompilerGenerated]
	[Token(Token = "0x40000C6")]
	private static EventHandler<ParentChangedEventArgs> ParentChanged; //Field offset: 0x0
	[FieldOffset(Offset = "0x70")]
	[Token(Token = "0x40000C7")]
	private TreeViewExpander m_expander; //Field offset: 0x70
	[FieldOffset(Offset = "0x78")]
	[SerializeField]
	[Token(Token = "0x40000C8")]
	private HorizontalLayoutGroup m_itemLayout; //Field offset: 0x78
	[FieldOffset(Offset = "0x80")]
	[Token(Token = "0x40000C9")]
	private Toggle m_toggle; //Field offset: 0x80
	[FieldOffset(Offset = "0x88")]
	[Token(Token = "0x40000CA")]
	private TreeView m_treeView; //Field offset: 0x88
	[FieldOffset(Offset = "0x90")]
	[Token(Token = "0x40000CB")]
	private int m_indent; //Field offset: 0x90
	[FieldOffset(Offset = "0x98")]
	[Token(Token = "0x40000CC")]
	private TreeViewItem m_parent; //Field offset: 0x98
	[FieldOffset(Offset = "0xA0")]
	[Token(Token = "0x40000CD")]
	private bool m_canExpand; //Field offset: 0xA0
	[FieldOffset(Offset = "0xA1")]
	[Token(Token = "0x40000CE")]
	private bool m_isExpanded; //Field offset: 0xA1

	[Token(Token = "0x1400001C")]
	public static event EventHandler<ParentChangedEventArgs> ParentChanged
	{
		[Address(RVA = "0x5D47A0", Offset = "0x5D39A0", Length = "0xD7")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(Delegate), Member = "Combine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Delegate), typeof(Delegate)}, ReturnType = typeof(Delegate))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F8B40")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
		[CompilerGenerated]
		[Token(Token = "0x60001D8")]
		 add { } //Length: 215
		[Address(RVA = "0x5D4AA0", Offset = "0x5D3CA0", Length = "0xD7")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(Delegate), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Delegate), typeof(Delegate)}, ReturnType = typeof(Delegate))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F8B40")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
		[CompilerGenerated]
		[Token(Token = "0x60001D9")]
		 remove { } //Length: 215
	}

	[Token(Token = "0x1700006E")]
	public bool CanExpand
	{
		[Address(RVA = "0x3D66E0", Offset = "0x3D58E0", Length = "0x8")]
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		[Token(Token = "0x60001E3")]
		 get { } //Length: 8
		[Address(RVA = "0x5D4B80", Offset = "0x5D3D80", Length = "0xA6")]
		[CalledBy(Type = typeof(TreeView), Member = "AddChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "RemoveChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "Expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "DestroyItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "DataBindItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ItemContainer)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
		[CallerCount(Count = 7)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(TreeViewExpander), Member = "UpdateState", ReturnType = typeof(void))]
		[Calls(Type = typeof(TreeViewItem), Member = "set_IsExpanded", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Token(Token = "0x60001E4")]
		 set { } //Length: 166
	}

	[Token(Token = "0x17000070")]
	public bool HasChildren
	{
		[Address(RVA = "0x5D4880", Offset = "0x5D3A80", Length = "0x16D")]
		[CalledBy(Type = typeof(TreeView), Member = "AddChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "DestroyItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewDropMarker), Member = "SetPosition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "FirstChild", ReturnType = typeof(TreeViewItem))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "LastChild", ReturnType = typeof(TreeViewItem))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "LastDescendant", ReturnType = typeof(TreeViewItem))]
		[CallerCount(Count = 7)]
		[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(ItemsControl), Member = "GetItemContainer", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(ItemContainer))]
		[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
		[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
		[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
		[Token(Token = "0x60001E7")]
		 get { } //Length: 365
	}

	[Token(Token = "0x1700006B")]
	public int Indent
	{
		[Address(RVA = "0x2FDE20", Offset = "0x2FD020", Length = "0x7")]
		[CallerCount(Count = 6)]
		[DeduplicatedMethod]
		[Token(Token = "0x60001DB")]
		 get { } //Length: 7
	}

	[Token(Token = "0x1700006F")]
	public bool IsExpanded
	{
		[Address(RVA = "0x5D49F0", Offset = "0x5D3BF0", Length = "0x8")]
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		[Token(Token = "0x60001E5")]
		 get { } //Length: 8
		[Address(RVA = "0x5D4C30", Offset = "0x5D3E30", Length = "0x153")]
		[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "set_CanExpand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "StartOverride", ReturnType = typeof(void))]
		[CallerCount(Count = 4)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(Toggle), Member = "set_isOn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
		[Calls(Type = typeof(TreeView), Member = "Collapse", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(TreeView), Member = "Expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[ContainsUnimplementedInstructions]
		[Token(Token = "0x60001E6")]
		 set { } //Length: 339
	}

	[Token(Token = "0x1700006D")]
	public virtual bool IsSelected
	{
		[Address(RVA = "0x347A30", Offset = "0x346C30", Length = "0x5")]
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		[Token(Token = "0x60001E1")]
		 get { } //Length: 5
		[Address(RVA = "0x5D4D90", Offset = "0x5D3F90", Length = "0x48")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(Toggle), Member = "set_isOn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(ItemContainer), Member = "set_IsSelected", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Token(Token = "0x60001E2")]
		 set { } //Length: 72
	}

	[Token(Token = "0x1700006C")]
	public TreeViewItem Parent
	{
		[Address(RVA = "0x2DD240", Offset = "0x2DC440", Length = "0x8")]
		[CallerCount(Count = 0)]
		[DeduplicatedMethod]
		[Token(Token = "0x60001DC")]
		 get { } //Length: 8
		[Address(RVA = "0x5D4DE0", Offset = "0x5D3FE0", Length = "0x36D")]
		[CalledBy(Type = typeof(TreeView), Member = "AddChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "Expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "Drop", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer[]), typeof(ItemContainer), typeof(ItemDropAction)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "SetNextSibling", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer), typeof(ItemContainer)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeView), Member = "SetPrevSibling", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer), typeof(ItemContainer)}, ReturnType = typeof(void))]
		[CallerCount(Count = 5)]
		[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
		[Calls(Type = typeof(TreeViewItem), Member = "SetIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(Int32&)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
		[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
		[Calls(Type = typeof(LayoutGroup), Member = "set_padding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RectOffset)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(RectOffset), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
		[Calls(Type = typeof(RectOffset), Member = "get_bottom", ReturnType = typeof(int))]
		[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(RectOffset), Member = "get_right", ReturnType = typeof(int))]
		[Calls(Type = typeof(TreeViewItem), Member = "ZeroIndent", ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(RectOffset), Member = "get_top", ReturnType = typeof(int))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsDeduplicatedMethods(Count = 1)]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x60001DD")]
		 set { } //Length: 877
	}

	[Token(Token = "0x1700006A")]
	private TreeView TreeView
	{
		[Address(RVA = "0x5D4A00", Offset = "0x5D3C00", Length = "0x99")]
		[CalledBy(Type = typeof(TreeViewItem), Member = "NextChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(TreeViewItem))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "set_Parent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "UpdateIndent", ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "SetIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(Int32&)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "set_IsExpanded", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "get_HasChildren", ReturnType = typeof(bool))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "FirstChild", ReturnType = typeof(TreeViewItem))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "LastChild", ReturnType = typeof(TreeViewItem))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "LastDescendant", ReturnType = typeof(TreeViewItem))]
		[CalledBy(Type = typeof(TreeViewItem), Member = "StartOverride", ReturnType = typeof(void))]
		[CallerCount(Count = 24)]
		[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(Component), Member = "GetComponentInParent", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, ReturnType = "T")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Token(Token = "0x60001DA")]
		private get { } //Length: 153
	}

	[Address(RVA = "0x5C58F0", Offset = "0x5C4AF0", Length = "0x11")]
	[CallerCount(Count = 0)]
	[CallsDeduplicatedMethods(Count = 1)]
	[DeduplicatedMethod]
	[Token(Token = "0x60001F0")]
	public TreeViewItem() { }

	[Address(RVA = "0x5D47A0", Offset = "0x5D39A0", Length = "0xD7")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Delegate), Member = "Combine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Delegate), typeof(Delegate)}, ReturnType = typeof(Delegate))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F8B40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[CompilerGenerated]
	[Token(Token = "0x60001D8")]
	public static void add_ParentChanged(EventHandler<ParentChangedEventArgs> value) { }

	[Address(RVA = "0x5D3520", Offset = "0x5D2720", Length = "0x124")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Component), Member = "GetComponent", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, ReturnType = "T")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(Selectable), Member = "set_interactable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Toggle), Member = "set_isOn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Component), Member = "GetComponentInChildren", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, ReturnType = "T")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(TreeViewExpander), Member = "UpdateState", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x60001ED")]
	protected virtual void AwakeOverride() { }

	[Address(RVA = "0x5D3650", Offset = "0x5D2850", Length = "0x187")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(GameObject), Member = "SetActive", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(TreeViewItem), Member = "ZeroIndent", ReturnType = typeof(void))]
	[Calls(Type = typeof(Toggle), Member = "set_isOn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(TreeViewExpander), Member = "UpdateState", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x60001EF")]
	public virtual void Clear() { }

	[Address(RVA = "0x5D37E0", Offset = "0x5D29E0", Length = "0xC7")]
	[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "SetNextSibling", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer), typeof(ItemContainer)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "SetPrevSibling", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer), typeof(ItemContainer)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(TreeViewItem), Member = "get_HasChildren", ReturnType = typeof(bool))]
	[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
	[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(ItemsControl), Member = "GetItemContainer", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(ItemContainer))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60001E9")]
	public TreeViewItem FirstChild() { }

	[Address(RVA = "0x3D66E0", Offset = "0x3D58E0", Length = "0x8")]
	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	[Token(Token = "0x60001E3")]
	public bool get_CanExpand() { }

	[Address(RVA = "0x5D4880", Offset = "0x5D3A80", Length = "0x16D")]
	[CalledBy(Type = typeof(TreeView), Member = "AddChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "DestroyItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewDropMarker), Member = "SetPosition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "FirstChild", ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "LastChild", ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "LastDescendant", ReturnType = typeof(TreeViewItem))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
	[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(ItemsControl), Member = "GetItemContainer", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(ItemContainer))]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Token(Token = "0x60001E7")]
	public bool get_HasChildren() { }

	[Address(RVA = "0x2FDE20", Offset = "0x2FD020", Length = "0x7")]
	[CallerCount(Count = 6)]
	[DeduplicatedMethod]
	[Token(Token = "0x60001DB")]
	public int get_Indent() { }

	[Address(RVA = "0x5D49F0", Offset = "0x5D3BF0", Length = "0x8")]
	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	[Token(Token = "0x60001E5")]
	public bool get_IsExpanded() { }

	[Address(RVA = "0x347A30", Offset = "0x346C30", Length = "0x5")]
	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	[Token(Token = "0x60001E1")]
	public virtual bool get_IsSelected() { }

	[Address(RVA = "0x2DD240", Offset = "0x2DC440", Length = "0x8")]
	[CallerCount(Count = 0)]
	[DeduplicatedMethod]
	[Token(Token = "0x60001DC")]
	public TreeViewItem get_Parent() { }

	[Address(RVA = "0x5D4A00", Offset = "0x5D3C00", Length = "0x99")]
	[CalledBy(Type = typeof(TreeViewItem), Member = "StartOverride", ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "LastDescendant", ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "FirstChild", ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "get_HasChildren", ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "LastChild", ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "SetIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(Int32&)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "UpdateIndent", ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "set_Parent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "NextChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "set_IsExpanded", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 24)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(Component), Member = "GetComponentInParent", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, ReturnType = "T")]
	[Token(Token = "0x60001DA")]
	private TreeView get_TreeView() { }

	[Address(RVA = "0x5D38B0", Offset = "0x5D2AB0", Length = "0xFA")]
	[CalledBy(Type = typeof(TreeView), Member = "CanDrop", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer[]), typeof(ItemContainer)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "MoveSubtree", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "NextChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "LastChild", ReturnType = typeof(TreeViewItem))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "LastDescendant", ReturnType = typeof(TreeViewItem))]
	[CallerCount(Count = 6)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60001E8")]
	public bool IsDescendantOf(TreeViewItem ancestor) { }

	[Address(RVA = "0x5D39B0", Offset = "0x5D2BB0", Length = "0x1F1")]
	[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(TreeViewItem), Member = "get_HasChildren", ReturnType = typeof(bool))]
	[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
	[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(TreeViewItem), Member = "IsDescendantOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x60001EB")]
	public TreeViewItem LastChild() { }

	[Address(RVA = "0x5D3BB0", Offset = "0x5D2DB0", Length = "0x1A4")]
	[CalledBy(Type = typeof(TreeView), Member = "AddChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "SetNextSibling", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer), typeof(ItemContainer)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(TreeViewItem), Member = "get_HasChildren", ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(TreeViewItem), Member = "IsDescendantOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x60001EC")]
	public TreeViewItem LastDescendant() { }

	[Address(RVA = "0x5D3D60", Offset = "0x5D2F60", Length = "0x245")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(TreeViewItem), Member = "IsDescendantOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
	[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(ItemsControl), Member = "GetItemContainer", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(ItemContainer))]
	[Token(Token = "0x60001EA")]
	public TreeViewItem NextChild(TreeViewItem currentChild) { }

	[Address(RVA = "0x5D4AA0", Offset = "0x5D3CA0", Length = "0xD7")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Delegate), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Delegate), typeof(Delegate)}, ReturnType = typeof(Delegate))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F8B40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[CompilerGenerated]
	[Token(Token = "0x60001D9")]
	public static void remove_ParentChanged(EventHandler<ParentChangedEventArgs> value) { }

	[Address(RVA = "0x5D4B80", Offset = "0x5D3D80", Length = "0xA6")]
	[CalledBy(Type = typeof(TreeView), Member = "AddChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "RemoveChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "Expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "DestroyItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "DataBindItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ItemContainer)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(TreeViewExpander), Member = "UpdateState", ReturnType = typeof(void))]
	[Calls(Type = typeof(TreeViewItem), Member = "set_IsExpanded", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60001E4")]
	public void set_CanExpand(bool value) { }

	[Address(RVA = "0x5D4C30", Offset = "0x5D3E30", Length = "0x153")]
	[CalledBy(Type = typeof(TreeView), Member = "OnTreeViewItemParentChanged", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(ParentChangedEventArgs)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "set_CanExpand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "StartOverride", ReturnType = typeof(void))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Toggle), Member = "set_isOn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(TreeView), Member = "Collapse", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(TreeView), Member = "Expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x60001E6")]
	public void set_IsExpanded(bool value) { }

	[Address(RVA = "0x5D4D90", Offset = "0x5D3F90", Length = "0x48")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Toggle), Member = "set_isOn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ItemContainer), Member = "set_IsSelected", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60001E2")]
	public virtual void set_IsSelected(bool value) { }

	[Address(RVA = "0x5D4DE0", Offset = "0x5D3FE0", Length = "0x36D")]
	[CalledBy(Type = typeof(TreeView), Member = "AddChild", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "Expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "Drop", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer[]), typeof(ItemContainer), typeof(ItemDropAction)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "SetNextSibling", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer), typeof(ItemContainer)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeView), Member = "SetPrevSibling", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ItemContainer), typeof(ItemContainer)}, ReturnType = typeof(void))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(RectOffset), Member = "get_top", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(TreeViewItem), Member = "ZeroIndent", ReturnType = typeof(void))]
	[Calls(Type = typeof(RectOffset), Member = "get_right", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(RectOffset), Member = "get_bottom", ReturnType = typeof(int))]
	[Calls(Type = typeof(RectOffset), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LayoutGroup), Member = "set_padding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RectOffset)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
	[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
	[Calls(Type = typeof(TreeViewItem), Member = "SetIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(Int32&)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x60001DD")]
	public void set_Parent(TreeViewItem value) { }

	[Address(RVA = "0x5D3FB0", Offset = "0x5D31B0", Length = "0x1F5")]
	[CalledBy(Type = typeof(TreeViewItem), Member = "set_Parent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "UpdateIndent", ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "SetIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(Int32&)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(RectOffset), Member = "set_left", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(TreeViewItem), Member = "SetIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(Int32&)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x60001E0")]
	private void SetIndent(TreeViewItem parent, ref int siblingIndex) { }

	[Address(RVA = "0x5D41B0", Offset = "0x5D33B0", Length = "0x275")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Toggle), Member = "set_isOn", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LayoutGroup), Member = "set_padding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RectOffset)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(RectOffset), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(RectOffset), Member = "get_bottom", ReturnType = typeof(int))]
	[Calls(Type = typeof(RectOffset), Member = "get_top", ReturnType = typeof(int))]
	[Calls(Type = typeof(RectOffset), Member = "get_right", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(System.Collections.Generic.HashSet`1<System.Object>), Member = "Contains", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(TreeViewItem), Member = "set_IsExpanded", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Token(Token = "0x60001EE")]
	protected virtual void StartOverride() { }

	[Address(RVA = "0x5D4430", Offset = "0x5D3630", Length = "0x224")]
	[CalledBy(Type = typeof(TreeView), Member = "UpdateIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(RectOffset), Member = "get_top", ReturnType = typeof(int))]
	[Calls(Type = typeof(TreeViewItem), Member = "SetIndent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem), typeof(Int32&)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Transform), Member = "GetSiblingIndex", ReturnType = typeof(int))]
	[Calls(Type = typeof(Component), Member = "get_transform", ReturnType = typeof(Transform))]
	[Calls(Type = typeof(LayoutGroup), Member = "set_padding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RectOffset)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(RectOffset), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(TreeViewItem), Member = "ZeroIndent", ReturnType = typeof(void))]
	[Calls(Type = typeof(RectOffset), Member = "get_right", ReturnType = typeof(int))]
	[Calls(Type = typeof(TreeViewItem), Member = "get_TreeView", ReturnType = typeof(TreeView))]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(RectOffset), Member = "get_bottom", ReturnType = typeof(int))]
	[Token(Token = "0x60001DE")]
	public void UpdateIndent() { }

	[Address(RVA = "0x5D4660", Offset = "0x5D3860", Length = "0x13D")]
	[CalledBy(Type = typeof(TreeViewItem), Member = "set_Parent", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TreeViewItem)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "UpdateIndent", ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TreeViewItem), Member = "Clear", ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Object), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object), typeof(Object)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(RectOffset), Member = "get_right", ReturnType = typeof(int))]
	[Calls(Type = typeof(RectOffset), Member = "get_top", ReturnType = typeof(int))]
	[Calls(Type = typeof(RectOffset), Member = "get_bottom", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(RectOffset), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LayoutGroup), Member = "set_padding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RectOffset)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60001DF")]
	private void ZeroIndent() { }

}

