namespace Mirror.BouncyCastle.Asn1;

[Token(Token = "0x20001A4")]
public class Asn1OutputStream : FilterStream
{
	[FieldOffset(Offset = "0x30")]
	[Token(Token = "0x400042F")]
	private readonly bool m_leaveOpen; //Field offset: 0x30

	[Address(RVA = "0x10E8A30", Offset = "0x10E7C30", Length = "0xB4")]
	[CalledBy(Type = typeof(DerOutputStream), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Stream), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DLOutputStream), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Stream), typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(FilterStream), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Stream)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F77")]
	protected private Asn1OutputStream(Stream output, bool leaveOpen) { }

	[Address(RVA = "0x10E7CE0", Offset = "0x10E6EE0", Length = "0x1AC")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(string), Member = "Equals", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(FilterStream), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Stream)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F74")]
	public static Asn1OutputStream Create(Stream output, string encoding) { }

	[Address(RVA = "0x10E7E90", Offset = "0x10E7090", Length = "0x1CB")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(string), Member = "Equals", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(FilterStream), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Stream)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F75")]
	public static Asn1OutputStream Create(Stream output, string encoding, bool leaveOpen) { }

	[Address(RVA = "0x10E8060", Offset = "0x10E7260", Length = "0x14")]
	[CallerCount(Count = 0)]
	[CallsDeduplicatedMethods(Count = 1)]
	[ContainsInvalidInstructions]
	[Token(Token = "0x6000F78")]
	protected virtual void Dispose(bool disposing) { }

	[Address(RVA = "0x10E8080", Offset = "0x10E7280", Length = "0x124")]
	[CalledBy(Type = typeof(ConstructedDerEncoding), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedDLEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedILEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F6BD0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F79")]
	internal void EncodeContents(IAsn1Encoding[] contentsEncodings) { }

	[Address(RVA = "0x2C3410", Offset = "0x2C2610", Length = "0x3")]
	[CallerCount(Count = 8626)]
	[DeduplicatedMethod]
	[Token(Token = "0x6000F7A")]
	private void FlushInternal() { }

	[Address(RVA = "0x10E8320", Offset = "0x10E7520", Length = "0x168")]
	[CalledBy(Type = typeof(DLSequence), Member = "GetEncoding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(DLSet), Member = "GetEncodingImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(DLSet), Member = "GetEncoding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(DLSequence), Member = "GetEncodingImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(DerSequence), Member = "GetEncoding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerSet), Member = "GetEncodingImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerSet), Member = "GetEncoding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(DerSequence), Member = "GetEncodingImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerSequence), Member = "GetEncoding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerOctetString), Member = "GetEncodingImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerOctetString), Member = "GetEncoding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerBitString), Member = "GetEncodingImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerBitString), Member = "GetEncoding", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CalledBy(Type = typeof(BerSequence), Member = "GetEncodingImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(int)}, ReturnType = typeof(IAsn1Encoding))]
	[CallerCount(Count = 14)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x6000F7D")]
	internal static IAsn1Encoding[] GetContentsEncodings(int encoding, Asn1Encodable[] elements) { }

	[Address(RVA = "0x10E81B0", Offset = "0x10E73B0", Length = "0x160")]
	[CalledBy(Type = typeof(DerSequence), Member = "GetEncodingDer", ReturnType = typeof(DerEncoding))]
	[CalledBy(Type = typeof(DerSequence), Member = "GetEncodingDerImplicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int)}, ReturnType = typeof(DerEncoding))]
	[CalledBy(Type = typeof(DerSet), Member = "CreateSortedDerEncodings", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1Encodable[])}, ReturnType = typeof(DerEncoding[]))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x6000F7E")]
	internal static DerEncoding[] GetContentsEncodingsDer(Asn1Encodable[] elements) { }

	[Address(RVA = "0x10E8490", Offset = "0x10E7690", Length = "0x83")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(string), Member = "Equals", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000F76")]
	internal static int GetEncodingType(string encoding) { }

	[Address(RVA = "0x10E8520", Offset = "0x10E7720", Length = "0x132")]
	[CalledBy(Type = typeof(Asn1OutputStream), Member = "GetLengthOfEncodingIL", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(IAsn1Encoding[])}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(ConstructedDerEncoding), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(DerEncoding[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedDLEncoding), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int), typeof(IAsn1Encoding[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedILEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.GetLength", ReturnType = typeof(int))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F6BD0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F7F")]
	internal static int GetLengthOfContents(IAsn1Encoding[] contentsEncodings) { }

	[Address(RVA = "0x10E8660", Offset = "0x10E7860", Length = "0x24")]
	[CalledBy(Type = typeof(DerUniversalString), Member = "GetString", ReturnType = typeof(string))]
	[CallerCount(Count = 1)]
	[Token(Token = "0x6000F80")]
	internal static int GetLengthOfDL(int dl) { }

	[Address(RVA = "0x10E8690", Offset = "0x10E7890", Length = "0x5E")]
	[CalledBy(Type = typeof(PrimitiveDerEncoding), Member = "GetLength", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(PrimitiveDerEncodingSuffixed), Member = "GetLength", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(PrimitiveEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.GetLength", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(PrimitiveEncodingSuffixed), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.GetLength", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(TaggedDerEncoding), Member = "GetLength", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(TaggedDLEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.GetLength", ReturnType = typeof(int))]
	[CallerCount(Count = 6)]
	[Token(Token = "0x6000F81")]
	internal static int GetLengthOfEncodingDL(int tagNo, int contentsLength) { }

	[Address(RVA = "0x10E8740", Offset = "0x10E7940", Length = "0x85")]
	[CalledBy(Type = typeof(TaggedILEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.GetLength", ReturnType = typeof(int))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180002270")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000F82")]
	internal static int GetLengthOfEncodingIL(int tagNo, IAsn1Encoding contentsEncoding) { }

	[Address(RVA = "0x10E86F0", Offset = "0x10E78F0", Length = "0x45")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Asn1OutputStream), Member = "GetLengthOfContents", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IAsn1Encoding[])}, ReturnType = typeof(int))]
	[Token(Token = "0x6000F83")]
	internal static int GetLengthOfEncodingIL(int tagNo, IAsn1Encoding[] contentsEncodings) { }

	[Address(RVA = "0x10E87D0", Offset = "0x10E79D0", Length = "0x21")]
	[CallerCount(Count = 0)]
	[Token(Token = "0x6000F84")]
	internal static int GetLengthOfIdentifier(int tagNo) { }

	[Address(RVA = "0x10E8800", Offset = "0x10E7A00", Length = "0xF1")]
	[CalledBy(Type = typeof(ConstructedDerEncoding), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedDLEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PrimitiveDerEncoding), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PrimitiveDerEncodingSuffixed), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PrimitiveEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PrimitiveEncodingSuffixed), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TaggedDerEncoding), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TaggedDLEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CallerCount(Count = 8)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x6000F7B")]
	internal void WriteDL(int dl) { }

	[Address(RVA = "0x10E8900", Offset = "0x10E7B00", Length = "0x129")]
	[CalledBy(Type = typeof(PrimitiveEncodingSuffixed), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedDerEncoding), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedDLEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ConstructedILEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PrimitiveDerEncoding), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PrimitiveDerEncodingSuffixed), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PrimitiveEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TaggedDerEncoding), Member = "Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TaggedDLEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TaggedILEncoding), Member = "Mirror.BouncyCastle.Asn1.IAsn1Encoding.Encode", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Asn1OutputStream)}, ReturnType = typeof(void))]
	[CallerCount(Count = 10)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x6000F7C")]
	internal void WriteIdentifier(int flags, int tagNo) { }

}

