namespace MoonSharp.Interpreter.Execution.VM;

[Token(Token = "0x2000146")]
internal class ByteCode : RefIdObject
{
	[Token(Token = "0x2000147")]
	private class SourceCodeStackGuard : IDisposable
	{
		[FieldOffset(Offset = "0x10")]
		[Token(Token = "0x40004EE")]
		private ByteCode m_Bc; //Field offset: 0x10

		[Address(RVA = "0x36B230", Offset = "0x36A430", Length = "0xE2")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(System.Collections.Generic.List`1<System.Object>), Member = "AddWithResize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
		[CallsDeduplicatedMethods(Count = 1)]
		[Token(Token = "0x6000C2A")]
		public SourceCodeStackGuard(SourceRef sref, ByteCode bc) { }

		[Address(RVA = "0x36B180", Offset = "0x36A380", Length = "0xA6")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(System.Collections.Generic.List`1<System.Object>), Member = "RemoveAt", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsDeduplicatedMethods(Count = 1)]
		[Token(Token = "0x6000C2B")]
		public override void Dispose() { }

	}

	[FieldOffset(Offset = "0x18")]
	[Token(Token = "0x40004E9")]
	public List<Instruction> Code; //Field offset: 0x18
	[CompilerGenerated]
	[FieldOffset(Offset = "0x20")]
	[Token(Token = "0x40004EA")]
	private Script <Script>k__BackingField; //Field offset: 0x20
	[FieldOffset(Offset = "0x28")]
	[Token(Token = "0x40004EB")]
	private List<SourceRef> m_SourceRefStack; //Field offset: 0x28
	[FieldOffset(Offset = "0x30")]
	[Token(Token = "0x40004EC")]
	private SourceRef m_CurrentSourceRef; //Field offset: 0x30
	[FieldOffset(Offset = "0x38")]
	[Token(Token = "0x40004ED")]
	internal LoopTracker LoopTracker; //Field offset: 0x38

	[Token(Token = "0x1700019F")]
	public private Script Script
	{
		[Address(RVA = "0x2F72B0", Offset = "0x2F64B0", Length = "0x5")]
		[CallerCount(Count = 11)]
		[CompilerGenerated]
		[DeduplicatedMethod]
		[Token(Token = "0x6000BFD")]
		 get { } //Length: 5
		[Address(RVA = "0x2F7320", Offset = "0x2F6520", Length = "0xD")]
		[CallerCount(Count = 10)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[CompilerGenerated]
		[DeduplicatedMethod]
		[Token(Token = "0x6000BFE")]
		private set { } //Length: 13
	}

	[Address(RVA = "0x351700", Offset = "0x350900", Length = "0x174")]
	[CalledBy(Type = typeof(Script), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CoreModules)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(FastStack`1), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 4)]
	[Token(Token = "0x6000BFF")]
	public ByteCode(Script script) { }

	[Address(RVA = "0x34F750", Offset = "0x34E950", Length = "0xB1")]
	[CallerCount(Count = 37)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(System.Collections.Generic.List`1<System.Object>), Member = "AddWithResize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Token(Token = "0x6000C07")]
	private Instruction AppendInstruction(Instruction c) { }

	[Address(RVA = "0x34F810", Offset = "0x34EA10", Length = "0x1BA")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(StringBuilder), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(StringBuilder), Member = "AppendFormat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object), typeof(object)}, ReturnType = typeof(StringBuilder))]
	[Calls(Type = typeof(StringBuilder), Member = "AppendFormat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object)}, ReturnType = typeof(StringBuilder))]
	[Calls(Type = typeof(File), Member = "WriteAllText", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 3)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000C03")]
	public void Dump(string file) { }

	[Address(RVA = "0x34F9D0", Offset = "0x34EBD0", Length = "0x9C")]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C17")]
	public Instruction Emit_Args(SymbolRef[] symbols) { }

	[Address(RVA = "0x34FA70", Offset = "0x34EC70", Length = "0xF8")]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(List`1), Member = "ToArray", ReturnType = "T[]")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C20")]
	public Instruction Emit_BeginFn(RuntimeScopeFrame stackFrame) { }

	[Address(RVA = "0x34FB70", Offset = "0x34ED70", Length = "0xAF")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionCallExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C0B")]
	public void Emit_Call(int argCount, string debugName) { }

	[Address(RVA = "0x34FC20", Offset = "0x34EE20", Length = "0xA4")]
	[CalledBy(Type = typeof(LabelStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C15")]
	public Instruction Emit_Clean(RuntimeScopeBlock runtimeScopeBlock) { }

	[Address(RVA = "0x34FCD0", Offset = "0x34EED0", Length = "0xAF")]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(System.Func`1<System.Int32>), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C16")]
	public Instruction Emit_Closure(SymbolRef[] symbols, int jmpnum) { }

	[Address(RVA = "0x34FD80", Offset = "0x34EF80", Length = "0x8E")]
	[CalledBy(Type = typeof(FunctionCallExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C28")]
	public Instruction Emit_Copy(int numval) { }

	[Address(RVA = "0x34FE10", Offset = "0x34F010", Length = "0xE9")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Math), Member = "Min", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(string), Member = "Substring", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(int)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Conditional("EMIT_DEBUG_OPS")]
	[Token(Token = "0x6000C11")]
	public void Emit_Debug(string str) { }

	[Address(RVA = "0x34FF00", Offset = "0x34F100", Length = "0xA2")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(IfStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(RepeatStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ScopeBlockStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(WhileStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C12")]
	public Instruction Emit_Enter(RuntimeScopeBlock runtimeScopeBlock) { }

	[Address(RVA = "0x34FFB0", Offset = "0x34F1B0", Length = "0xA2")]
	[CalledBy(Type = typeof(Loop), Member = "CompileBreak", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C14")]
	public Instruction Emit_Exit(RuntimeScopeBlock runtimeScopeBlock) { }

	[Address(RVA = "0x350060", Offset = "0x34F260", Length = "0x8E")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C1D")]
	public Instruction Emit_ExpTuple(int stackOffset) { }

	[Address(RVA = "0x3500F0", Offset = "0x34F2F0", Length = "0x8E")]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C1A")]
	public Instruction Emit_Incr(int i) { }

	[Address(RVA = "0x350260", Offset = "0x34F460", Length = "0xC7")]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "SetMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionCallExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(IndexExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C26")]
	public Instruction Emit_Index(DynValue index = null, bool isNameIndex = false, bool isExpList = false) { }

	[Address(RVA = "0x350180", Offset = "0x34F380", Length = "0xDA")]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "SetMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(IndexExpression), Member = "CompileAssignment", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C27")]
	public Instruction Emit_IndexSet(int stackofs, int tupleidx, DynValue index = null, bool isNameIndex = false, bool isExpList = false) { }

	[Address(RVA = "0x350330", Offset = "0x34F530", Length = "0x9C")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C09")]
	public Instruction Emit_Invalid(string type) { }

	[Address(RVA = "0x3503D0", Offset = "0x34F5D0", Length = "0x7F")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C1C")]
	public Instruction Emit_IterPrep() { }

	[Address(RVA = "0x350450", Offset = "0x34F650", Length = "0x7F")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C1E")]
	public Instruction Emit_IterUpd() { }

	[Address(RVA = "0x3504D0", Offset = "0x34F6D0", Length = "0x9E")]
	[CalledBy(Type = typeof(WhileStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Loop), Member = "CompileBreak", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(GotoStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(IfStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(RepeatStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(BinaryOperatorExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 13)]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C0E")]
	public Instruction Emit_Jump(OpCode jumpOpCode, int idx, int optPar = 0) { }

	[Address(RVA = "0x350570", Offset = "0x34F770", Length = "0xA2")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(IfStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(RepeatStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ScopeBlockStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(WhileStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 8)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C13")]
	public Instruction Emit_Leave(RuntimeScopeBlock runtimeScopeBlock) { }

	[Address(RVA = "0x350620", Offset = "0x34F820", Length = "0x9C")]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(LiteralExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C0D")]
	public Instruction Emit_Literal(DynValue value) { }

	[Address(RVA = "0x3506C0", Offset = "0x34F8C0", Length = "0x225")]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "SetMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(SymbolRefExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ByteCode), Member = "Emit_Load", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SymbolRef)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(ByteCode), Member = "Emit_Store", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SymbolRef), typeof(int), typeof(int)}, ReturnType = typeof(int))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001F20")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(ByteCode), Member = "Emit_Load", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SymbolRef)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001D10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(DynValue), Member = "NewString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001F40")]
	[CallsDeduplicatedMethods(Count = 4)]
	[Token(Token = "0x6000C22")]
	public int Emit_Load(SymbolRef sym) { }

	[Address(RVA = "0x3508F0", Offset = "0x34FAF0", Length = "0xBE")]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C1F")]
	public Instruction Emit_Meta(string funcName, OpCodeMetadataType metaType, DynValue value = null) { }

	[Address(RVA = "0x3509B0", Offset = "0x34FBB0", Length = "0x8E")]
	[CalledBy(Type = typeof(ExprListExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C0F")]
	public Instruction Emit_MkTuple(int cnt) { }

	[Address(RVA = "0x350A40", Offset = "0x34FC40", Length = "0x8F")]
	[CalledBy(Type = typeof(TableConstructor), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C1B")]
	public Instruction Emit_NewTable(bool shared) { }

	[Address(RVA = "0x350AD0", Offset = "0x34FCD0", Length = "0x9C")]
	[CalledBy(Type = typeof(Loader_Fast), Member = "LoadChunk", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(SourceCode), typeof(ByteCode)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(Loader_Fast), Member = "LoadFunction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(SourceCode), typeof(ByteCode), typeof(bool)}, ReturnType = typeof(int))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C08")]
	public Instruction Emit_Nop(string comment) { }

	[Address(RVA = "0x350B70", Offset = "0x34FD70", Length = "0x121")]
	[CalledBy(Type = typeof(BinaryOperatorExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(UnaryOperatorExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 3)]
	[Token(Token = "0x6000C10")]
	public Instruction Emit_Operator(OpCode opcode) { }

	[Address(RVA = "0x350CA0", Offset = "0x34FEA0", Length = "0x8E")]
	[CalledBy(Type = "MoonSharp.Interpreter.Tree.Statements.FunctionDefinitionStatement+<>c__DisplayClass9_0", Member = "<Compile>b__1", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(AssignmentStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionCallStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = "MoonSharp.Interpreter.Tree.Statements.FunctionDefinitionStatement+<>c__DisplayClass9_0", Member = "<Compile>b__0", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "SetFunction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 10)]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C0A")]
	public Instruction Emit_Pop(int num = 1) { }

	[Address(RVA = "0x350D30", Offset = "0x34FF30", Length = "0x8E")]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ReturnStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C18")]
	public Instruction Emit_Ret(int retvals) { }

	[Address(RVA = "0x350DC0", Offset = "0x34FFC0", Length = "0x7F")]
	[CalledBy(Type = typeof(AdjustmentExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C21")]
	public Instruction Emit_Scalar() { }

	[Address(RVA = "0x350E40", Offset = "0x350040", Length = "0x250")]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = "MoonSharp.Interpreter.Tree.Statements.FunctionDefinitionStatement+<>c__DisplayClass9_0", Member = "<Compile>b__0", ReturnType = typeof(int))]
	[CalledBy(Type = "MoonSharp.Interpreter.Tree.Statements.FunctionDefinitionStatement+<>c__DisplayClass9_0", Member = "<Compile>b__1", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "SetFunction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(SymbolRefExpression), Member = "CompileAssignment", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[CallerCount(Count = 8)]
	[Calls(Type = typeof(ByteCode), Member = "Emit_Load", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SymbolRef)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001F20")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001D10")]
	[Calls(Type = typeof(DynValue), Member = "NewString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001F40")]
	[CallsDeduplicatedMethods(Count = 4)]
	[Token(Token = "0x6000C23")]
	public int Emit_Store(SymbolRef sym, int stackofs, int tupleidx) { }

	[Address(RVA = "0x3510A0", Offset = "0x3502A0", Length = "0xA2")]
	[CalledBy(Type = typeof(FunctionCallExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C29")]
	public Instruction Emit_Swap(int p1, int p2) { }

	[Address(RVA = "0x351150", Offset = "0x350350", Length = "0x8F")]
	[CalledBy(Type = typeof(TableConstructor), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C25")]
	public Instruction Emit_TblInitI(bool lastpos) { }

	[Address(RVA = "0x3511E0", Offset = "0x3503E0", Length = "0x7F")]
	[CalledBy(Type = typeof(TableConstructor), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C24")]
	public Instruction Emit_TblInitN() { }

	[Address(RVA = "0x351260", Offset = "0x350460", Length = "0xAF")]
	[CalledBy(Type = typeof(FunctionCallExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C0C")]
	public void Emit_ThisCall(int argCount, string debugName) { }

	[Address(RVA = "0x351310", Offset = "0x350510", Length = "0x8E")]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(ByteCode), Member = "AppendInstruction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(Instruction))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C19")]
	public Instruction Emit_ToNum(int stage = 0) { }

	[Address(RVA = "0x3513A0", Offset = "0x3505A0", Length = "0x111")]
	[CalledBy(Type = typeof(Loader_Fast), Member = "LoadChunk", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(SourceCode), typeof(ByteCode)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(System.Func`1<System.Int32>), typeof(string)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(Loader_Fast), Member = "LoadFunction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(SourceCode), typeof(ByteCode), typeof(bool)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(ReturnStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(IfStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ScopeBlockStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionCallStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(BreakStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(AssignmentStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CallerCount(Count = 14)]
	[Calls(Type = typeof(System.Collections.Generic.List`1<System.Object>), Member = "AddWithResize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C00")]
	public IDisposable EnterSource(SourceRef sref) { }

	[Address(RVA = "0x2F72B0", Offset = "0x2F64B0", Length = "0x5")]
	[CallerCount(Count = 11)]
	[CompilerGenerated]
	[DeduplicatedMethod]
	[Token(Token = "0x6000BFD")]
	public Script get_Script() { }

	[Address(RVA = "0x3514C0", Offset = "0x3506C0", Length = "0x3E")]
	[CalledBy(Type = typeof(ChunkStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(LabelStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Loader_Fast), Member = "LoadChunk", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(SourceCode), typeof(ByteCode)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000C05")]
	public int GetJumpPointForLastInstruction() { }

	[Address(RVA = "0x351500", Offset = "0x350700", Length = "0x3C")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(IfStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(RepeatStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(WhileStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(BinaryOperatorExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(System.Func`1<System.Int32>), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 15)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000C04")]
	public int GetJumpPointForNextInstruction() { }

	[Address(RVA = "0x351540", Offset = "0x350740", Length = "0x59")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C06")]
	public Instruction GetLastInstruction() { }

	[Address(RVA = "0x3515A0", Offset = "0x3507A0", Length = "0x9C")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(RepeatStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(WhileStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 10)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(System.Collections.Generic.List`1<System.Object>), Member = "RemoveAt", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000C02")]
	public void PopSourceRef() { }

	[Address(RVA = "0x351640", Offset = "0x350840", Length = "0xB1")]
	[CalledBy(Type = typeof(ForEachLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ForLoopStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(RepeatStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(WhileStatement), Member = "Compile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(FunctionDefinitionExpression), Member = "CompileBody", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ByteCode), typeof(string)}, ReturnType = typeof(int))]
	[CallerCount(Count = 10)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(System.Collections.Generic.List`1<System.Object>), Member = "AddWithResize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Token(Token = "0x6000C01")]
	public void PushSourceRef(SourceRef sref) { }

	[Address(RVA = "0x2F7320", Offset = "0x2F6520", Length = "0xD")]
	[CallerCount(Count = 10)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[CompilerGenerated]
	[DeduplicatedMethod]
	[Token(Token = "0x6000BFE")]
	private void set_Script(Script value) { }

}

