namespace System;

[Token(Token = "0x20001A6")]
public abstract class Delegate : ICloneable, ISerializable
{
	[FieldOffset(Offset = "0x10")]
	[Token(Token = "0x40006FB")]
	private IntPtr method_ptr; //Field offset: 0x10
	[FieldOffset(Offset = "0x18")]
	[Token(Token = "0x40006FC")]
	private IntPtr invoke_impl; //Field offset: 0x18
	[FieldOffset(Offset = "0x20")]
	[Token(Token = "0x40006FD")]
	private object m_target; //Field offset: 0x20
	[FieldOffset(Offset = "0x28")]
	[Token(Token = "0x40006FE")]
	private IntPtr method; //Field offset: 0x28
	[FieldOffset(Offset = "0x30")]
	[Token(Token = "0x40006FF")]
	private IntPtr delegate_trampoline; //Field offset: 0x30
	[FieldOffset(Offset = "0x38")]
	[Token(Token = "0x4000700")]
	private IntPtr extra_arg; //Field offset: 0x38
	[FieldOffset(Offset = "0x40")]
	[Token(Token = "0x4000701")]
	private IntPtr method_code; //Field offset: 0x40
	[FieldOffset(Offset = "0x48")]
	[Token(Token = "0x4000702")]
	private IntPtr interp_method; //Field offset: 0x48
	[FieldOffset(Offset = "0x50")]
	[Token(Token = "0x4000703")]
	private IntPtr interp_invoke_impl; //Field offset: 0x50
	[FieldOffset(Offset = "0x58")]
	[Token(Token = "0x4000704")]
	private MethodInfo method_info; //Field offset: 0x58
	[FieldOffset(Offset = "0x60")]
	[Token(Token = "0x4000705")]
	private MethodInfo original_method_info; //Field offset: 0x60
	[FieldOffset(Offset = "0x68")]
	[Token(Token = "0x4000706")]
	private DelegateData data; //Field offset: 0x68
	[FieldOffset(Offset = "0x70")]
	[Token(Token = "0x4000707")]
	private bool method_is_virtual; //Field offset: 0x70

	[Token(Token = "0x1700015F")]
	public MethodInfo Method
	{
		[Address(RVA = "0x13F0A50", Offset = "0x13EFC50", Length = "0x14")]
		[CallerCount(Count = 25)]
		[CallsUnknownMethods(Count = 1)]
		[DeduplicatedMethod]
		[Token(Token = "0x6000F29")]
		 get { } //Length: 20
	}

	[Token(Token = "0x17000160")]
	public object Target
	{
		[Address(RVA = "0x2F72B0", Offset = "0x2F64B0", Length = "0x5")]
		[CallerCount(Count = 11)]
		[DeduplicatedMethod]
		[Token(Token = "0x6000F2B")]
		 get { } //Length: 5
	}

	[Address(RVA = "0x14F2970", Offset = "0x14F1B70", Length = "0x5")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A4B0")]
	[Token(Token = "0x6000F47")]
	internal static MulticastDelegate AllocDelegateLike_internal(Delegate d) { }

	[Address(RVA = "0x14F4970", Offset = "0x14F3B70", Length = "0x170")]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(MethodInfo), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "get_IsValueType", ReturnType = typeof(bool))]
	[Calls(Type = typeof(Enum), Member = "GetUnderlyingType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 3)]
	[CallsUnknownMethods(Count = 3)]
	[Token(Token = "0x6000F2D")]
	private static bool arg_type_match(Type delArgType, Type argType) { }

	[Address(RVA = "0x14F4AF0", Offset = "0x14F3CF0", Length = "0x151")]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(MethodInfo), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Type), Member = "get_IsValueType", ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "get_IsByRef", ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 3)]
	[CallsUnknownMethods(Count = 2)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000F2E")]
	private static bool arg_type_match_this(Type delArgType, Type argType, bool boxedThis) { }

	[Address(RVA = "0x14F2980", Offset = "0x14F1B80", Length = "0x5")]
	[CallerCount(Count = 36)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1802143C0")]
	[DeduplicatedMethod]
	[Token(Token = "0x6000F3A")]
	public override object Clone() { }

	[Address(RVA = "0x14F2B50", Offset = "0x14F1D50", Length = "0x1BD")]
	[CalledBy(Type = typeof(DelegateSerializationHolder), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(StreamingContext)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(object), Member = "GetType", ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001F20")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001DB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(string), Member = "Format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object), typeof(object)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	[ComVisible(True)]
	[Token(Token = "0x6000F41")]
	public static Delegate Combine(Delegate[] delegates) { }

	[Address(RVA = "0x14F29F0", Offset = "0x14F1BF0", Length = "0x15F")]
	[CallerCount(Count = 419)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001F20")]
	[Calls(Type = typeof(object), Member = "GetType", ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001DB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(string), Member = "Format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object), typeof(object)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F40")]
	public static Delegate Combine(Delegate a, Delegate b) { }

	[Address(RVA = "0x14F2990", Offset = "0x14F1B90", Length = "0x55")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_class_get_static_field_data")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(MulticastNotSupportedException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Token(Token = "0x6000F42")]
	protected override Delegate CombineImpl(Delegate d) { }

	[Address(RVA = "0x14F2D20", Offset = "0x14F1F20", Length = "0xE7")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(Delegate), Member = "GetCandidateMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string), typeof(BindingFlags), typeof(bool), typeof(bool)}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A500")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000F39")]
	public static Delegate CreateDelegate(Type type, object target, string method, bool ignoreCase) { }

	[Address(RVA = "0x14F39E0", Offset = "0x14F2BE0", Length = "0xEE")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Delegate), Member = "GetCandidateMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string), typeof(BindingFlags), typeof(bool), typeof(bool)}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A500")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x6000F37")]
	public static Delegate CreateDelegate(Type type, Type target, string method) { }

	[Address(RVA = "0x14F3B20", Offset = "0x14F2D20", Length = "0x105")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Delegate), Member = "GetCandidateMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string), typeof(BindingFlags), typeof(bool), typeof(bool)}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A500")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x6000F36")]
	public static Delegate CreateDelegate(Type type, Type target, string method, bool ignoreCase, bool throwOnBindFailure) { }

	[Address(RVA = "0x14F3900", Offset = "0x14F2B00", Length = "0xD7")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(Delegate), Member = "GetCandidateMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string), typeof(BindingFlags), typeof(bool), typeof(bool)}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A500")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000F34")]
	public static Delegate CreateDelegate(Type type, object target, string method) { }

	[Address(RVA = "0x14F3810", Offset = "0x14F2A10", Length = "0xED")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(Delegate), Member = "GetCandidateMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string), typeof(BindingFlags), typeof(bool), typeof(bool)}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A500")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000F38")]
	public static Delegate CreateDelegate(Type type, object target, string method, bool ignoreCase, bool throwOnBindFailure) { }

	[Address(RVA = "0x14F3AD0", Offset = "0x14F2CD0", Length = "0x25")]
	[CalledBy(Type = "Battlehub.UIControls.MenuControl.MenuCreator", Member = "Awake", ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(MethodInfo), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[Token(Token = "0x6000F32")]
	public static Delegate CreateDelegate(Type type, MethodInfo method, bool throwOnBindFailure) { }

	[Address(RVA = "0x14F3B00", Offset = "0x14F2D00", Length = "0x1F")]
	[CalledBy(Type = typeof(RuntimeMethodInfo), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = "MoonSharp.Interpreter.Interop.EventMemberDescriptor+<>c__DisplayClass20_0", Member = "<RegisterCallback>b__0", ReturnType = typeof(Delegate))]
	[CalledBy(Type = "UnityEngine.Events.InvokableCall", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(MethodInfo)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.Events.InvokableCall`1", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(MethodInfo)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.Events.InvokableCall`2", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(MethodInfo)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.Events.InvokableCall`3", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(MethodInfo)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.Events.InvokableCall`4", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(MethodInfo)}, ReturnType = typeof(void))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(MethodInfo), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[Token(Token = "0x6000F31")]
	public static Delegate CreateDelegate(Type type, object firstArgument, MethodInfo method) { }

	[Address(RVA = "0x14F2E10", Offset = "0x14F2010", Length = "0x9C1")]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(MethodInfo)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(MethodInfo), typeof(bool)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(MethodInfo)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = "System.DelegateSerializationHolder+DelegateEntry", Member = "DeserializeDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(int)}, ReturnType = typeof(Delegate))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(Delegate), Member = "arg_type_match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(Delegate), Member = "arg_type_match_this", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(bool)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A500")]
	[Calls(Type = typeof(Type), Member = "get_IsByRef", ReturnType = typeof(bool))]
	[Calls(Type = typeof(MethodBase), Member = "get_IsStatic", ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Delegate), Member = "return_type_match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Type), Member = "GetMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(Type), Member = "get_IsValueType", ReturnType = typeof(bool))]
	[Calls(Type = typeof(TargetParameterCountException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 23)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000F30")]
	private static Delegate CreateDelegate(Type type, object firstArgument, MethodInfo method, bool throwOnBindFailure, bool allowClosed) { }

	[Address(RVA = "0x14F37E0", Offset = "0x14F29E0", Length = "0x24")]
	[CalledBy(Type = typeof(RuntimeMethodInfo), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = "MoonSharp.Interpreter.ModuleRegister", Member = "RegisterModuleType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"MoonSharp.Interpreter.Table", typeof(Type)}, ReturnType = "MoonSharp.Interpreter.Table")]
	[CalledBy(Type = "System.Xml.SecureStringHasher", Member = "GetHashCodeDelegate", ReturnType = "System.Xml.SecureStringHasher+HashCodeOfStringDelegate")]
	[CalledBy(Type = "System.Xml.XmlQualifiedName", Member = "GetHashCodeDelegate", ReturnType = "System.Xml.XmlQualifiedName+HashCodeOfStringDelegate")]
	[CalledBy(Type = "UnityEngine.UI.ReflectionMethodsCache", Member = ".ctor", ReturnType = typeof(void))]
	[CalledBy(Type = "Unity.Properties.ReflectedMemberProperty`2", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Unity.Properties.IMemberInfo", typeof(string)}, ReturnType = typeof(void))]
	[CallerCount(Count = 14)]
	[Calls(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(MethodInfo), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[Token(Token = "0x6000F33")]
	public static Delegate CreateDelegate(Type type, MethodInfo method) { }

	[Address(RVA = "0x14F2D10", Offset = "0x14F1F10", Length = "0x5")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020A500")]
	[Token(Token = "0x6000F2C")]
	internal static Delegate CreateDelegate_internal(Type type, object target, MethodInfo info, bool throwOnBindFailure) { }

	[Address(RVA = "0x14F3C30", Offset = "0x14F2E30", Length = "0x1E1")]
	[CalledBy(Type = typeof(MulticastDelegate), Member = "Equals", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 5)]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x6000F3B")]
	public virtual bool Equals(object obj) { }

	[Address(RVA = "0x13F0A50", Offset = "0x13EFC50", Length = "0x14")]
	[CallerCount(Count = 25)]
	[CallsUnknownMethods(Count = 1)]
	[DeduplicatedMethod]
	[Token(Token = "0x6000F29")]
	public MethodInfo get_Method() { }

	[Address(RVA = "0x2F72B0", Offset = "0x2F64B0", Length = "0x5")]
	[CallerCount(Count = 11)]
	[DeduplicatedMethod]
	[Token(Token = "0x6000F2B")]
	public object get_Target() { }

	[Address(RVA = "0x14F3E20", Offset = "0x14F3020", Length = "0x502")]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(string)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(string), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(string), typeof(bool)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = "System.DelegateSerializationHolder+DelegateEntry", Member = "DeserializeDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SerializationInfo), typeof(int)}, ReturnType = typeof(Delegate))]
	[CallerCount(Count = 7)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(Delegate), Member = "return_type_match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[Calls(Type = typeof(Type), Member = "GetMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(BindingFlags), typeof(Binder), typeof(Type[]), typeof(ParameterModifier[])}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(Type), Member = "GetMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(MethodInfo))]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F72D0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 4)]
	[CallsUnknownMethods(Count = 6)]
	[Token(Token = "0x6000F35")]
	private static MethodInfo GetCandidateMethod(Type type, Type target, string method, BindingFlags bflags, bool ignoreCase, bool throwOnBindFailure) { }

	[Address(RVA = "0x14F4330", Offset = "0x14F3530", Length = "0x94")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 2)]
	[CallsUnknownMethods(Count = 3)]
	[DeduplicatedMethod]
	[Token(Token = "0x6000F3C")]
	public virtual int GetHashCode() { }

	[Address(RVA = "0x14F43D0", Offset = "0x14F35D0", Length = "0x9A")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Token(Token = "0x6000F3F")]
	public override Delegate[] GetInvocationList() { }

	[Address(RVA = "0x14F4470", Offset = "0x14F3670", Length = "0x113")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020ABE0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(RuntimeMethodInfo), Member = "GetMethodFromHandleNoGenericCheck", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeMethodHandle)}, ReturnType = typeof(MethodBase))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000F3D")]
	protected override MethodInfo GetMethodImpl() { }

	[Address(RVA = "0x14F4590", Offset = "0x14F3790", Length = "0x239")]
	[CallerCount(Count = 0)]
	[Calls(Type = "System.DelegateSerializationHolder+DelegateEntry", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Delegate), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(int), Member = "ToString", ReturnType = typeof(string))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(SerializationInfo), Member = "AddValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(SerializationInfo), Member = "SetType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type)}, ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 2)]
	[DeduplicatedMethod]
	[Token(Token = "0x6000F3E")]
	public override void GetObjectData(SerializationInfo info, StreamingContext context) { }

	[Address(RVA = "0x14F47D0", Offset = "0x14F39D0", Length = "0x5")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18020ABE0")]
	[Token(Token = "0x6000F2A")]
	private MethodInfo GetVirtualMethod_internal() { }

	[Address(RVA = "0x14F4C50", Offset = "0x14F3E50", Length = "0x28")]
	[CalledBy(Type = "UnityEngine.UIElements.ListView", Member = "set_destroyItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkLoop+<>c__DisplayClass5_0", Member = "<AddToPlayerLoop>b__0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.LowLevel.PlayerLoopSystem"}, ReturnType = typeof(bool))]
	[CalledBy(Type = "Mirror.NetworkLoop+<>c__DisplayClass4_0", Member = "<FindPlayerLoopEntryIndex>b__0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.LowLevel.PlayerLoopSystem"}, ReturnType = typeof(bool))]
	[CalledBy(Type = "UnityEngine.UIElements.VisualElement+BaseVisualElementScheduledItem", Member = "Every", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(long)}, ReturnType = "UnityEngine.UIElements.IVisualElementScheduledItem")]
	[CalledBy(Type = "UnityEngine.UIElements.EventCallbackFunctor`2", Member = "IsEquivalentTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(long), typeof(Delegate)}, ReturnType = typeof(bool))]
	[CalledBy(Type = "UnityEngine.UIElements.EventCallbackFunctor`1", Member = "IsEquivalentTo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(long), typeof(Delegate)}, ReturnType = typeof(bool))]
	[CalledBy(Type = "UnityEngine.UIElements.Column", Member = "set_makeCell", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.Column", Member = "set_makeHeader", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteCalls.Invoker", Member = "AreEqual", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), "Mirror.RemoteCalls.RemoteCallType", "Mirror.RemoteCalls.RemoteCallDelegate"}, ReturnType = typeof(bool))]
	[CalledBy(Type = "UnityEngine.UIElements.ListView", Member = "set_unbindItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`2<VisualElement, Int32>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.BaseListView", Member = "set_onAdd", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`1<BaseListView>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.BaseListView", Member = "set_overridingAddButtonBehavior", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`2<BaseListView, Button>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.BaseListView", Member = "set_makeNoneElement", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.BaseListView", Member = "set_makeFooter", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.BaseListView", Member = "set_makeHeader", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.DynamicAtlas", Member = "set_customFilter", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.UIElements.DynamicAtlasCustomFilter"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.InputForUI.EventProvider+<>c__DisplayClass8_0", Member = "<Unsubscribe>b__0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.InputForUI.EventProvider+Registration"}, ReturnType = typeof(bool))]
	[CalledBy(Type = "UnityEngine.UIElements.BaseListView", Member = "set_onRemove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`1<BaseListView>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteCalls.RemoteProcedureCalls", Member = "CheckIfDelegateExists", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), "Mirror.RemoteCalls.RemoteCallType", "Mirror.RemoteCalls.RemoteCallDelegate", typeof(ushort)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 19)]
	[CallsUnknownMethods(Count = 1)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000F45")]
	public static bool op_Equality(Delegate d1, Delegate d2) { }

	[Address(RVA = "0x14F4C80", Offset = "0x14F3E80", Length = "0x42")]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView", Member = "set_bindItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`2<VisualElement, Int32>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.IMGUIContainer", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Action)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.IMGUIContainer", Member = "set_onGUIHandler", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Action)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>", "System.Action`2<VisualElement, Int32>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView", Member = ".ctor", ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView", Member = "set_destroyItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView", Member = "set_unbindItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`2<VisualElement, Int32>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "System.Net.Security.SslStream", Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Stream), typeof(bool), "System.Net.Security.RemoteCertificateValidationCallback", "System.Net.Security.LocalCertificateSelectionCallback"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView", Member = "set_itemTemplate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.UIElements.VisualTreeAsset"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView+UxmlTraits", Member = "Init", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.UIElements.VisualElement", "UnityEngine.UIElements.IUxmlAttributes", "UnityEngine.UIElements.CreationContext"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.ListView", Member = "set_bindItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Action`2<VisualElement, Int32>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.ListView", Member = "set_itemTemplate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.UIElements.VisualTreeAsset"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.ListView", Member = "set_makeItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.ListView+UxmlTraits", Member = "Init", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.UIElements.VisualElement", "UnityEngine.UIElements.IUxmlAttributes", "UnityEngine.UIElements.CreationContext"}, ReturnType = typeof(void))]
	[CalledBy(Type = "System.Net.Security.SslStream", Member = "SetAndVerifySelectionCallback", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Net.Security.LocalCertificateSelectionCallback"}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.TreeView", Member = "set_makeItem", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Func`1<VisualElement>"}, ReturnType = typeof(void))]
	[CalledBy(Type = "System.Net.Security.SslStream", Member = "SetAndVerifyValidationCallback", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Net.Security.RemoteCertificateValidationCallback"}, ReturnType = typeof(void))]
	[CallerCount(Count = 19)]
	[CallsUnknownMethods(Count = 1)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000F46")]
	public static bool op_Inequality(Delegate d1, Delegate d2) { }

	[Address(RVA = "0x14F4810", Offset = "0x14F3A10", Length = "0x15E")]
	[CallerCount(Count = 370)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180214040")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001F20")]
	[Calls(Type = typeof(object), Member = "GetType", ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180001DB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(string), Member = "Format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object), typeof(object)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F43")]
	public static Delegate Remove(Delegate source, Delegate value) { }

	[Address(RVA = "0x14F47E0", Offset = "0x14F39E0", Length = "0x2D")]
	[CallerCount(Count = 0)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000F44")]
	protected override Delegate RemoveImpl(Delegate d) { }

	[Address(RVA = "0x14F4CD0", Offset = "0x14F3ED0", Length = "0x200")]
	[CalledBy(Type = typeof(Delegate), Member = "CreateDelegate", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(object), typeof(MethodInfo), typeof(bool), typeof(bool)}, ReturnType = typeof(Delegate))]
	[CalledBy(Type = typeof(Delegate), Member = "GetCandidateMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(string), typeof(BindingFlags), typeof(bool), typeof(bool)}, ReturnType = typeof(MethodInfo))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "get_IsValueType", ReturnType = typeof(bool))]
	[Calls(Type = typeof(Enum), Member = "GetUnderlyingType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 4)]
	[CallsUnknownMethods(Count = 3)]
	[Token(Token = "0x6000F2F")]
	private static bool return_type_match(Type delReturnType, Type returnType) { }

}

