namespace Polytoria.Datamodel;

[Extension]
[Token(Token = "0x2000339")]
public static class NetMessageReadWriteFunctions
{

	[Address(RVA = "0x706CA0", Offset = "0x705EA0", Length = "0x1C5")]
	[CalledBy(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadNetMessage", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(NetMessage))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(System.Collections.Generic.Dictionary`2<System.Object, System.Boolean>), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(System.Collections.Generic.Dictionary`2<System.Object, System.Boolean>), Member = "Add", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
	[Calls(Type = typeof(NetworkReaderExtensions), Member = "ReadInt", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F72D0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(NetworkReaderExtensions), Member = "ReadString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(string), Member = "Format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object), typeof(object)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(Debug), Member = "LogError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[CallsUnknownMethods(Count = 1)]
	[DeduplicatedMethod]
	[Token(Token = "0x6001F0D")]
	public static Dictionary<String, T> ReadDictionary(NetworkReader reader) { }

	[Address(RVA = "0x43A2D0", Offset = "0x4394D0", Length = "0x1EB")]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeUserCode_InvokeCmd__NetMessage__NetworkConnectionToClient", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkBehaviour), typeof(NetworkReader), typeof(NetworkConnectionToClient)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeUserCode_InvokeTargetRpc__NetworkConnection__NetMessage", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkBehaviour), typeof(NetworkReader), typeof(NetworkConnectionToClient)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeUserCode_InvokeClientRpc__NetMessage", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkBehaviour), typeof(NetworkReader), typeof(NetworkConnectionToClient)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(System.Collections.Generic.Dictionary`2<System.String, System.Object>))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(System.Collections.Generic.Dictionary`2<System.String, System.Int32>))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(System.Collections.Generic.Dictionary`2<System.String, System.Single>))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = "System.Collections.Generic.Dictionary`2<String, T>")]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(System.Collections.Generic.Dictionary`2<System.String, UnityEngine.Vector2>))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector3)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(System.Collections.Generic.Dictionary`2<System.String, UnityEngine.Vector3>))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "ReadDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Color)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkReader)}, ReturnType = typeof(System.Collections.Generic.Dictionary`2<System.String, UnityEngine.Color>))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Extension]
	[Token(Token = "0x6001F0F")]
	public static NetMessage ReadNetMessage(NetworkReader reader) { }

	[Address(RVA = "0x707BA0", Offset = "0x706DA0", Length = "0x185")]
	[CalledBy(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteNetMessage", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(NetMessage)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(Dictionary`2), Member = "get_Count", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(NetworkWriter), Member = "Write", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(NetworkWriterExtensions), Member = "WriteString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAE0")]
	[Calls(Type = typeof(NetworkWriterExtensions), Member = "WriteInt", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Dictionary`2), Member = "GetEnumerator", ReturnType = "System.Collections.Generic.Dictionary`2<TKey, TValue>+Enumerator<TKey, TValue>")]
	[Calls(Type = typeof(System.Collections.Generic.Dictionary`2+Enumerator<System.Object, System.Boolean>), Member = "MoveNext", ReturnType = typeof(bool))]
	[CallsDeduplicatedMethods(Count = 2)]
	[ContainsUnimplementedInstructions]
	[DeduplicatedMethod]
	[Extension]
	[Token(Token = "0x6001F0C")]
	private static void WriteDictionary(NetworkWriter writer, Dictionary<String, T> dict) { }

	[Address(RVA = "0x43A4C0", Offset = "0x4396C0", Length = "0x130")]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeServer", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetMessage)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeClient", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetMessage), typeof(Player)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeClients", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetMessage)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeCmd", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetMessage), typeof(NetworkConnectionToClient)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeTargetRpc", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkConnection), typeof(NetMessage)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(NetworkEvent), Member = "InvokeClientRpc", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetMessage)}, ReturnType = typeof(void))]
	[CallerCount(Count = 6)]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector3)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(System.Collections.Generic.Dictionary`2<System.String, UnityEngine.Vector3>)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(System.Collections.Generic.Dictionary`2<System.String, UnityEngine.Vector2>)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), "System.Collections.Generic.Dictionary`2<String, T>"}, ReturnType = typeof(void))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(System.Collections.Generic.Dictionary`2<System.String, System.Single>)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(System.Collections.Generic.Dictionary`2<System.String, System.Object>)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Color)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(System.Collections.Generic.Dictionary`2<System.String, UnityEngine.Color>)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(NetMessageReadWriteFunctions), Member = "WriteDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(NetworkWriter), typeof(System.Collections.Generic.Dictionary`2<System.String, System.Int32>)}, ReturnType = typeof(void))]
	[Extension]
	[Token(Token = "0x6001F0E")]
	public static void WriteNetMessage(NetworkWriter writer, NetMessage value) { }

}

