namespace MoonSharp.Interpreter.CoreLib.StringLib;

[Token(Token = "0x2000189")]
internal class KopiLua_StringLib : LuaBase
{
	[CompilerGenerated]
	[Token(Token = "0x200018D")]
	private sealed class <>c__DisplayClass29_0
	{
		[FieldOffset(Offset = "0x10")]
		[Token(Token = "0x400061F")]
		public ScriptExecutionContext executionContext; //Field offset: 0x10

		[Address(RVA = "0x2BC7B0", Offset = "0x2BB9B0", Length = "0x7")]
		[CallerCount(Count = 2609)]
		[CallsDeduplicatedMethods(Count = 1)]
		[DeduplicatedMethod]
		[Token(Token = "0x6000EAE")]
		public <>c__DisplayClass29_0() { }

		[Address(RVA = "0x3A2AD0", Offset = "0x3A1CD0", Length = "0xB6")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(ScriptExecutionContext), Member = "get_AdditionalData", ReturnType = typeof(object))]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(KopiLua_StringLib), Member = "gmatch_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), "MoonSharp.Interpreter.CoreLib.StringLib.KopiLua_StringLib+GMatchAuxData"}, ReturnType = typeof(int))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
		[Token(Token = "0x6000EAF")]
		internal int <gmatch_aux_2>b__0(LuaState L) { }

	}

	[Token(Token = "0x200018C")]
	private class GMatchAuxData
	{
		[FieldOffset(Offset = "0x10")]
		[Token(Token = "0x400061B")]
		public CharPtr S; //Field offset: 0x10
		[FieldOffset(Offset = "0x18")]
		[Token(Token = "0x400061C")]
		public CharPtr P; //Field offset: 0x18
		[FieldOffset(Offset = "0x20")]
		[Token(Token = "0x400061D")]
		public uint LS; //Field offset: 0x20
		[FieldOffset(Offset = "0x24")]
		[Token(Token = "0x400061E")]
		public uint POS; //Field offset: 0x24

		[Address(RVA = "0x2BC7B0", Offset = "0x2BB9B0", Length = "0x7")]
		[CallerCount(Count = 2609)]
		[CallsDeduplicatedMethods(Count = 1)]
		[DeduplicatedMethod]
		[Token(Token = "0x6000EAD")]
		public GMatchAuxData() { }

	}

	[Token(Token = "0x200018A")]
	internal class MatchState
	{
		[Token(Token = "0x200018B")]
		internal class capture_
		{
			[FieldOffset(Offset = "0x10")]
			[Token(Token = "0x4000619")]
			public CharPtr init; //Field offset: 0x10
			[FieldOffset(Offset = "0x18")]
			[Token(Token = "0x400061A")]
			public int len; //Field offset: 0x18

			[Address(RVA = "0x2BC7B0", Offset = "0x2BB9B0", Length = "0x7")]
			[CallerCount(Count = 2609)]
			[CallsDeduplicatedMethods(Count = 1)]
			[DeduplicatedMethod]
			[Token(Token = "0x6000EAC")]
			public capture_() { }

		}

		[FieldOffset(Offset = "0x10")]
		[Token(Token = "0x4000613")]
		public int matchdepth; //Field offset: 0x10
		[FieldOffset(Offset = "0x18")]
		[Token(Token = "0x4000614")]
		public CharPtr src_init; //Field offset: 0x18
		[FieldOffset(Offset = "0x20")]
		[Token(Token = "0x4000615")]
		public CharPtr src_end; //Field offset: 0x20
		[FieldOffset(Offset = "0x28")]
		[Token(Token = "0x4000616")]
		public LuaState L; //Field offset: 0x28
		[FieldOffset(Offset = "0x30")]
		[Token(Token = "0x4000617")]
		public int level; //Field offset: 0x30
		[FieldOffset(Offset = "0x38")]
		[Token(Token = "0x4000618")]
		public capture_[] capture; //Field offset: 0x38

		[Address(RVA = "0x39FA60", Offset = "0x39EC60", Length = "0x118")]
		[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_find_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
		[CalledBy(Type = typeof(KopiLua_StringLib), Member = "gmatch_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), "MoonSharp.Interpreter.CoreLib.StringLib.KopiLua_StringLib+GMatchAuxData"}, ReturnType = typeof(int))]
		[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_gsub", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
		[CallerCount(Count = 3)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
		[CallsDeduplicatedMethods(Count = 2)]
		[Token(Token = "0x6000EAB")]
		public MatchState() { }

	}

	[Token(Token = "0x400060A")]
	public const int LUA_MAXCAPTURES = 32; //Field offset: 0x0
	[Token(Token = "0x400060B")]
	public const int CAP_UNFINISHED = -1; //Field offset: 0x0
	[Token(Token = "0x400060C")]
	public const int CAP_POSITION = -2; //Field offset: 0x0
	[Token(Token = "0x400060D")]
	public const int MAXCCALLS = 200; //Field offset: 0x0
	[Token(Token = "0x400060E")]
	public const char L_ESC = '\u25'; //Field offset: 0x0
	[Token(Token = "0x400060F")]
	public const string SPECIALS = "^$*+?.([%-"; //Field offset: 0x0
	[Token(Token = "0x4000610")]
	public const int MAX_ITEM = 512; //Field offset: 0x0
	[Token(Token = "0x4000611")]
	public const string FLAGS = "-+ #0"; //Field offset: 0x0
	[Token(Token = "0x4000612")]
	public static readonly int MAX_FORMAT; //Field offset: 0x0

	[Address(RVA = "0x37C3C0", Offset = "0x37B5C0", Length = "0x75")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000EAA")]
	private static KopiLua_StringLib() { }

	[Address(RVA = "0x2FF940", Offset = "0x2FEB40", Length = "0x7")]
	[CallerCount(Count = 83)]
	[CallsDeduplicatedMethods(Count = 1)]
	[DeduplicatedMethod]
	[Token(Token = "0x6000EA9")]
	public KopiLua_StringLib() { }

	[Address(RVA = "0x37C440", Offset = "0x37B640", Length = "0x1D6")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "add_value", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(LuaLBuffer), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(uint)}, ReturnType = typeof(char))]
	[Calls(Type = typeof(LuaBase), Member = "isdigit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "push_onecapture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddLString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddChar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(char)}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x6000EA1")]
	private static void add_s(MatchState ms, LuaLBuffer b, CharPtr s, CharPtr e) { }

	[Address(RVA = "0x37C620", Offset = "0x37B820", Length = "0x268")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_gsub", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(LuaBase), Member = "LuaIsString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "add_s", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(LuaLBuffer), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushLString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaPop", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLTypeName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(LuaBase), Member = "LuaToBoolean", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaGetTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "push_onecapture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaCall", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "push_captures", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Token(Token = "0x6000EA2")]
	private static void add_value(MatchState ms, LuaLBuffer b, CharPtr s, CharPtr e) { }

	[Address(RVA = "0x37C890", Offset = "0x37BA90", Length = "0x100")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "strlen", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(uint)}, ReturnType = typeof(char))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "strcpy", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x6000EA6")]
	private static void addintlen(CharPtr form) { }

	[Address(RVA = "0x37C9A0", Offset = "0x37BBA0", Length = "0x21E")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddChar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(char)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddLString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(char), Member = "IsNumber", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(string), Member = "Format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 7)]
	[Token(Token = "0x6000EA4")]
	private static void addquoted(LuaState L, LuaLBuffer b, int arg) { }

	[Address(RVA = "0x37CBC0", Offset = "0x37BDC0", Length = "0xB2")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000E8B")]
	private static int capture_to_close(MatchState ms) { }

	[Address(RVA = "0x37CC80", Offset = "0x37BE80", Length = "0x14F")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Token(Token = "0x6000E8A")]
	private static int check_capture(MatchState ms, int l) { }

	[Address(RVA = "0x37CDD0", Offset = "0x37BFD0", Length = "0x26C")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CharPtr), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LUA_QL", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 9)]
	[Token(Token = "0x6000E8C")]
	private static CharPtr classend(MatchState ms, CharPtr p) { }

	[Address(RVA = "0x37D040", Offset = "0x37C240", Length = "0x1A6")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000E94")]
	private static CharPtr end_capture(MatchState ms, CharPtr s, CharPtr p) { }

	[Address(RVA = "0x37D1F0", Offset = "0x37C3F0", Length = "0xAB")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "LUA_QL", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000EA0")]
	private static int gfind_nodef(LuaState L) { }

	[Address(RVA = "0x37D390", Offset = "0x37C590", Length = "0x1C3")]
	[CalledBy(Type = typeof(<>c__DisplayClass29_0), Member = "<gmatch_aux_2>b__0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "push_captures", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(MatchState), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThanOrEqual", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Token(Token = "0x6000E9D")]
	private static int gmatch_aux(LuaState L, GMatchAuxData auxdata) { }

	[Address(RVA = "0x37D2A0", Offset = "0x37C4A0", Length = "0xED")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(Func`2), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(IntPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ScriptExecutionContext), Member = "EmulateClassicCall", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CallbackArguments), typeof(string), typeof(System.Func`2<MoonSharp.Interpreter.Interop.LuaStateInterop.LuaState, System.Int32>)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000E9E")]
	private static DynValue gmatch_aux_2(ScriptExecutionContext executionContext, CallbackArguments args) { }

	[Address(RVA = "0x37D560", Offset = "0x37C760", Length = "0x105")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(LuaBase), Member = "memchr", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(char), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "memcmp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000E97")]
	private static CharPtr lmemfind(CharPtr s1, uint l1, CharPtr s2, uint l2) { }

	[Address(RVA = "0x37DA20", Offset = "0x37CC20", Length = "0x8DC")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "max_expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "min_expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "start_capture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "end_capture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_find_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "gmatch_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(GMatchAuxData)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_gsub", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CallerCount(Count = 9)]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(String[])}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CharPtr), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "matchbracketclass", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "isdigit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "max_expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "start_capture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "end_capture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LUA_QL", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match_capture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "singlematch", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "matchbalance", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "classend", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsDeduplicatedMethods(Count = 14)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000E96")]
	private static CharPtr match(MatchState ms, CharPtr s, CharPtr p) { }

	[Address(RVA = "0x37D670", Offset = "0x37C870", Length = "0x206")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "memcmp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Token(Token = "0x6000E95")]
	private static CharPtr match_capture(MatchState ms, CharPtr s, int l) { }

	[Address(RVA = "0x37D880", Offset = "0x37CA80", Length = "0xB8")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "matchbracketclass", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "singlematch", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(LuaBase), Member = "tolower", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(char))]
	[Calls(Type = typeof(LuaBase), Member = "isalpha", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18037D992")]
	[Calls(Type = typeof(LuaBase), Member = "iscntrl", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(LuaBase), Member = "isdigit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(LuaBase), Member = "isgraph", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(LuaBase), Member = "islower", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[CallsUnknownMethods(Count = 1)]
	[ContainsInvalidInstructions]
	[Token(Token = "0x6000E8D")]
	private static int match_class(char c, char cl) { }

	[Address(RVA = "0x37E320", Offset = "0x37D520", Length = "0x1B3")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 9)]
	[Token(Token = "0x6000E90")]
	private static CharPtr matchbalance(MatchState ms, CharPtr s, CharPtr p) { }

	[Address(RVA = "0x37E4E0", Offset = "0x37D6E0", Length = "0x1DB")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "singlematch", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match_class", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char), typeof(char)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 6)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000E8E")]
	private static int matchbracketclass(int c, CharPtr p, CharPtr ec) { }

	[Address(RVA = "0x37E6C0", Offset = "0x37D8C0", Length = "0x157")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "singlematch", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000E91")]
	private static CharPtr max_expand(MatchState ms, CharPtr s, CharPtr p, CharPtr ep) { }

	[Address(RVA = "0x37E820", Offset = "0x37DA20", Length = "0x130")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "singlematch", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000E92")]
	private static CharPtr min_expand(MatchState ms, CharPtr s, CharPtr p, CharPtr ep) { }

	[Address(RVA = "0x37C360", Offset = "0x37B560", Length = "0x59")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(string), Member = "Replace", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000EA8")]
	private static string PatchPattern(string charPtr) { }

	[Address(RVA = "0x37E960", Offset = "0x37DB60", Length = "0x10")]
	[CallerCount(Count = 0)]
	[Token(Token = "0x6000E89")]
	private static int posrelat(int pos, uint len) { }

	[Address(RVA = "0x37E970", Offset = "0x37DB70", Length = "0xFF")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_find_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "gmatch_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(GMatchAuxData)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "add_value", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(LuaLBuffer), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "push_onecapture", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x6000E99")]
	private static int push_captures(MatchState ms, CharPtr s, CharPtr e) { }

	[Address(RVA = "0x37EA70", Offset = "0x37DC70", Length = "0x1A3")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "push_captures", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "add_s", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(LuaLBuffer), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "add_value", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(LuaLBuffer), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushLString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushInteger", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x6000E98")]
	private static void push_onecapture(MatchState ms, int i, CharPtr s, CharPtr e) { }

	[Address(RVA = "0x37EC20", Offset = "0x37DE20", Length = "0x2FF")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_format", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "strchr", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(char)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "isdigit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(LuaBase), Member = "strncpy", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 12)]
	[Token(Token = "0x6000EA5")]
	private static CharPtr scanformat(LuaState L, CharPtr strfrmt, CharPtr form) { }

	[Address(RVA = "0x37EF20", Offset = "0x37E120", Length = "0x125")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "max_expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "min_expand", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match_class", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(char), typeof(char)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "matchbracketclass", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 3)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000E8F")]
	private static int singlematch(int c, CharPtr p, CharPtr ep) { }

	[Address(RVA = "0x37F050", Offset = "0x37E250", Length = "0x149")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000E93")]
	private static CharPtr start_capture(MatchState ms, CharPtr s, CharPtr p, int what) { }

	[Address(RVA = "0x37F680", Offset = "0x37E880", Length = "0x4F")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "str_find_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[Token(Token = "0x6000E9B")]
	public static int str_find(LuaState L) { }

	[Address(RVA = "0x37F1A0", Offset = "0x37E3A0", Length = "0x4D0")]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(KopiLua_StringLib), Member = "str_match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThanOrEqual", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(MatchState), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushInteger", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "memcmp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "memchr", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(char), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushNil", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(LuaBase), Member = "strpbrk", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LuaToBoolean", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLOptInteger", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(string), Member = "Replace", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "push_captures", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[CallsDeduplicatedMethods(Count = 4)]
	[Token(Token = "0x6000E9A")]
	private static int str_find_aux(LuaState L, int find) { }

	[Address(RVA = "0x37F6D0", Offset = "0x37E8D0", Length = "0x838")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(LuaBase), Member = "strchr", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(char)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180003B10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(LuaBase), Member = "sprintf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr), typeof(Object[])}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "strlen", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddLString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddChar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(char)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLPushResult", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(LuaBase), Member = "LUA_QL", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string), typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(string), typeof(Object[])}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(int)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Equality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "addquoted", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(LuaLBuffer), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "LuaGetTop", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(LuaLBuffer), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Char[])}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLArgError", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "scanformat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLCheckNumber", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(double))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "addintlen", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE430")]
	[CallsDeduplicatedMethods(Count = 10)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000EA7")]
	public static int str_format(LuaState L) { }

	[Address(RVA = "0x37FF60", Offset = "0x37F160", Length = "0x294")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CallbackFunction), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(System.Func`3<MoonSharp.Interpreter.ScriptExecutionContext, MoonSharp.Interpreter.CallbackArguments, MoonSharp.Interpreter.DynValue>), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "ArgAsType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int), typeof(DataType), typeof(bool)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(DynValue), Member = "get_String", ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(string), Member = "Replace", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CharPtr), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(DynValue), Member = "NewCallback", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CallbackFunction)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(LuaState), Member = "Push", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x6000E9F")]
	public static int str_gmatch(LuaState L) { }

	[Address(RVA = "0x380200", Offset = "0x37F400", Length = "0x397")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(LuaBase), Member = "LuaLArgCheck", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(bool), typeof(int), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_Subtraction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddChar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(char)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CharPtr), Member = "op_GreaterThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "add_value", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(LuaLBuffer), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CharPtr), Member = "op_Inequality", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "match", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MatchState), typeof(CharPtr), typeof(CharPtr)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CharPtr), Member = "op_Addition", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CharPtr), typeof(uint)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(MatchState), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLAddLString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer), typeof(CharPtr), typeof(uint)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CharPtr), Member = "next", ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLOptInt", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(LuaBase), Member = "LuaType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(string), Member = "Replace", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CharPtr), Member = "op_Implicit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(CharPtr))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LuaBase), Member = "LuaPushInteger", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaLBuffer), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(LuaBase), Member = "LuaLPushResult", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaLBuffer)}, ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 5)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000EA3")]
	public static int str_gsub(LuaState L) { }

	[Address(RVA = "0x3805A0", Offset = "0x37F7A0", Length = "0x4C")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(KopiLua_StringLib), Member = "str_find_aux", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(int))]
	[Token(Token = "0x6000E9C")]
	public static int str_match(LuaState L) { }

}

