namespace Mirror.BouncyCastle.Pkcs;

[Token(Token = "0x2000016")]
public static class PrivateKeyInfoFactory
{

	[Address(RVA = "0x10C0990", Offset = "0x10BFB90", Length = "0xA")]
	[CalledBy(Type = "Mirror.Transports.Encryption.EncryptionCredentials", Member = "SerializePrivateKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(AsymmetricKeyParameter)}, ReturnType = "System.Byte[]")]
	[CalledBy(Type = "Mirror.Transports.Encryption.EncryptionCredentials", Member = "SaveToFile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(PrivateKeyInfoFactory), Member = "CreatePrivateKeyInfo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(AsymmetricKeyParameter), typeof(Asn1Set)}, ReturnType = typeof(PrivateKeyInfo))]
	[Token(Token = "0x6000081")]
	public static PrivateKeyInfo CreatePrivateKeyInfo(AsymmetricKeyParameter privateKey) { }

	[Address(RVA = "0x10BF4F0", Offset = "0x10BE6F0", Length = "0x1492")]
	[CalledBy(Type = typeof(PrivateKeyInfoFactory), Member = "CreatePrivateKeyInfo", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(AsymmetricKeyParameter)}, ReturnType = typeof(PrivateKeyInfo))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(ECPrivateKeyStructure), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(BigInteger), typeof(DerBitString), typeof(Asn1Encodable)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Ed25519PrivateKeyParameters), Member = "GeneratePublicKey", ReturnType = typeof(Ed25519PublicKeyParameters))]
	[Calls(Type = typeof(Ed25519PublicKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(Ed448PrivateKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(Ed448PrivateKeyParameters), Member = "GeneratePublicKey", ReturnType = typeof(Ed448PublicKeyParameters))]
	[Calls(Type = typeof(Ed448PublicKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(X25519PrivateKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(X25519PrivateKeyParameters), Member = "GeneratePublicKey", ReturnType = typeof(X25519PublicKeyParameters))]
	[Calls(Type = typeof(X25519PublicKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(X448PrivateKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(X448PrivateKeyParameters), Member = "GeneratePublicKey", ReturnType = typeof(X448PublicKeyParameters))]
	[Calls(Type = typeof(PrivateKeyInfo), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(AlgorithmIdentifier), typeof(Asn1Encodable), typeof(Asn1Set), typeof(Byte[])}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Ed25519PrivateKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(ArgumentNullException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(NotImplementedException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x180002030")]
	[Calls(Type = typeof(Platform), Member = "GetTypeName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(X448PublicKeyParameters), Member = "GetEncoded", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(Gost3410PublicKeyAlgParameters), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DerObjectIdentifier), typeof(DerObjectIdentifier)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(X962Parameters), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(X9ECParameters)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ArgumentException), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(ElGamalParameter), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(BigInteger), typeof(BigInteger)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DerInteger), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(BigInteger)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DsaParameter), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(BigInteger), typeof(BigInteger), typeof(BigInteger)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DHParameter), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(BigInteger), typeof(BigInteger), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(PrivateKeyInfo), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(AlgorithmIdentifier), typeof(Asn1Encodable), typeof(Asn1Set)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(RsaPrivateKeyStructure), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(BigInteger), typeof(BigInteger), typeof(BigInteger), typeof(BigInteger), typeof(BigInteger), typeof(BigInteger), typeof(BigInteger), typeof(BigInteger)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ECKeyPairGenerator), Member = "GetCorrespondingPublicKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ECPrivateKeyParameters)}, ReturnType = typeof(ECPublicKeyParameters))]
	[Calls(Type = typeof(Gost3410PublicKeyAlgParameters), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DerObjectIdentifier), typeof(DerObjectIdentifier), typeof(DerObjectIdentifier)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(BigInteger), Member = "get_BitLength", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(BigInteger), Member = "ToByteArray", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(Array), Member = "Copy", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Array), typeof(int), typeof(Array), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DerOctetString), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Byte[])}, ReturnType = typeof(void))]
	[Calls(Type = typeof(PrivateKeyInfo), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(AlgorithmIdentifier), typeof(Asn1Encodable)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(X9ECPoint), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ECPoint), typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ECDomainParameters), Member = "GetSeed", ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(X9ECParameters), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ECCurve), typeof(X9ECPoint), typeof(BigInteger), typeof(BigInteger), typeof(Byte[])}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DerBitString), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Byte[])}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsDeduplicatedMethods(Count = 14)]
	[CallsUnknownMethods(Count = 6)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000082")]
	public static PrivateKeyInfo CreatePrivateKeyInfo(AsymmetricKeyParameter privateKey, Asn1Set attributes) { }

	[Address(RVA = "0x10C09A0", Offset = "0x10BFBA0", Length = "0x111")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(BigInteger), Member = "ToByteArray", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(Byte[]))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(Array), Member = "Copy", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Array), typeof(int), typeof(Array), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Token(Token = "0x6000083")]
	private static void ExtractBytes(Byte[] encKey, int size, int offSet, BigInteger bI) { }

}

