namespace UnityEngine;

[Token(Token = "0x200000F")]
public class GUILayout
{
	[Token(Token = "0x2000010")]
	private sealed class LayoutedWindow
	{
		[FieldOffset(Offset = "0x10")]
		[Token(Token = "0x400005F")]
		private readonly WindowFunction m_Func; //Field offset: 0x10
		[FieldOffset(Offset = "0x18")]
		[Token(Token = "0x4000060")]
		private readonly Rect m_ScreenRect; //Field offset: 0x18
		[FieldOffset(Offset = "0x28")]
		[Token(Token = "0x4000061")]
		private readonly GUILayoutOption[] m_Options; //Field offset: 0x28
		[FieldOffset(Offset = "0x30")]
		[Token(Token = "0x4000062")]
		private readonly GUIStyle m_Style; //Field offset: 0x30

		[Address(RVA = "0x19BA920", Offset = "0x19B9B20", Length = "0x69")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[CallsDeduplicatedMethods(Count = 1)]
		[Token(Token = "0x6000103")]
		internal LayoutedWindow(WindowFunction f, Rect screenRect, GUIContent content, GUILayoutOption[] options, GUIStyle style) { }

		[Address(RVA = "0x19BA7B0", Offset = "0x19B99B0", Length = "0x163")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = typeof(GUILayoutEntry), Member = "set_style", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIStyle)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsDeduplicatedMethods(Count = 1)]
		[CallsUnknownMethods(Count = 3)]
		[Token(Token = "0x6000104")]
		public void DoWindow(int windowID) { }

	}


	[Address(RVA = "0x19A5ED0", Offset = "0x19A50D0", Length = "0x2A1")]
	[CalledBy(Type = typeof(GUILayout), Member = "BeginArea", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIUtility), Member = "CheckOnGUI", ReturnType = typeof(void))]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "BeginLayoutArea", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIStyle), typeof(Type)}, ReturnType = typeof(GUILayoutGroup))]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(GUI), Member = "BeginGroup", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle), typeof(Vector2)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x60000F6")]
	public static void BeginArea(Rect screenRect, GUIContent content, GUIStyle style) { }

	[Address(RVA = "0x19A5E20", Offset = "0x19A5020", Length = "0xA1")]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "DrawPlayerReadyButton", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkClient", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.GUIConsole", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkPingDisplay", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomManager", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "DrawPlayerReadyState", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "StopButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "kcp2k.KcpTransport", Member = "OnGUIStatistics", ReturnType = typeof(void))]
	[CalledBy(Type = "Edgegap.EdgegapKcpTransport", Member = "OnGUIRelay", ReturnType = typeof(void))]
	[CallerCount(Count = 13)]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayout), Member = "BeginArea", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(GUIStyle), Member = "get_none", ReturnType = typeof(GUIStyle))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Token(Token = "0x60000F5")]
	public static void BeginArea(Rect screenRect) { }

	[Address(RVA = "0x19A6220", Offset = "0x19A5420", Length = "0x16B")]
	[CalledBy(Type = typeof(GUILayout), Member = "BeginHorizontal", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "BeginLayoutGroup", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIStyle), typeof(GUILayoutOption[]), typeof(Type)}, ReturnType = typeof(GUILayoutGroup))]
	[Calls(Type = typeof(GUIStyle), Member = "get_none", ReturnType = typeof(GUIStyle))]
	[Calls(Type = typeof(GUI), Member = "Box", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000F0")]
	public static void BeginHorizontal(GUIContent content, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6390", Offset = "0x19A5590", Length = "0x6B")]
	[CalledBy(Type = "Mirror.NetworkClient", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkPingDisplay", Member = "OnGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayout), Member = "BeginHorizontal", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(void))]
	[Token(Token = "0x60000EF")]
	public static void BeginHorizontal(GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6180", Offset = "0x19A5380", Length = "0x96")]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StartButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StopButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(double), typeof(int), typeof(string), typeof(int), typeof(Color)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Edgegap.EdgegapKcpTransport", Member = "OnGUIRelay", ReturnType = typeof(void))]
	[CallerCount(Count = 9)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIStyle), Member = "get_none", ReturnType = typeof(GUIStyle))]
	[ContainsInvalidInstructions]
	[Token(Token = "0x60000EE")]
	public static void BeginHorizontal(GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6400", Offset = "0x19A5600", Length = "0xCB")]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUILayout), Member = "BeginScrollView", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2), typeof(bool), typeof(bool), typeof(GUIStyle), typeof(GUIStyle), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Vector2))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000F8")]
	public static Vector2 BeginScrollView(Vector2 scrollPosition, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A64D0", Offset = "0x19A56D0", Length = "0x1CB")]
	[CalledBy(Type = "Mirror.GUIConsole", Member = "OnGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(GUIStyle), Member = "get_rawName", ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(GUISkin), Member = "FindStyle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIStyle))]
	[Calls(Type = typeof(GUILayout), Member = "BeginScrollView", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2), typeof(bool), typeof(bool), typeof(GUIStyle), typeof(GUIStyle), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Vector2))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000F9")]
	public static Vector2 BeginScrollView(Vector2 scrollPosition, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A66A0", Offset = "0x19A58A0", Length = "0x2E9")]
	[CalledBy(Type = typeof(GUILayout), Member = "BeginScrollView", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2), typeof(GUILayoutOption[])}, ReturnType = typeof(Vector2))]
	[CalledBy(Type = typeof(GUILayout), Member = "BeginScrollView", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector2), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Vector2))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIUtility), Member = "CheckOnGUI", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "BeginLayoutGroup", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIStyle), typeof(GUILayoutOption[]), typeof(Type)}, ReturnType = typeof(GUILayoutGroup))]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(GUI), Member = "BeginScrollView", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(Vector2), typeof(Rect), typeof(bool), typeof(bool), typeof(GUIStyle), typeof(GUIStyle), typeof(GUIStyle)}, ReturnType = typeof(Vector2))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x60000FA")]
	public static Vector2 BeginScrollView(Vector2 scrollPosition, bool alwaysShowHorizontal, bool alwaysShowVertical, GUIStyle horizontalScrollbar, GUIStyle verticalScrollbar, GUIStyle background, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6B00", Offset = "0x19A5D00", Length = "0x1AE")]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "OnWindow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnClientGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnServerGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Authenticate", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_General", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(double), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Traffic", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(long), typeof(long)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Cpu", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(double), typeof(double), typeof(double), typeof(double), typeof(double)}, ReturnType = typeof(void))]
	[CalledBy(Type = "kcp2k.KcpTransport", Member = "OnGUIStatistics", ReturnType = typeof(void))]
	[CallerCount(Count = 11)]
	[Calls(Type = typeof(GUIStyle), Member = "get_none", ReturnType = typeof(GUIStyle))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "BeginLayoutGroup", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIStyle), typeof(GUILayoutOption[]), typeof(Type)}, ReturnType = typeof(GUILayoutGroup))]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(GUI), Member = "Box", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Token(Token = "0x60000F2")]
	public static void BeginVertical(GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6990", Offset = "0x19A5B90", Length = "0x16B")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "BeginLayoutGroup", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIStyle), typeof(GUILayoutOption[]), typeof(Type)}, ReturnType = typeof(GUILayoutGroup))]
	[Calls(Type = typeof(GUIStyle), Member = "get_none", ReturnType = typeof(GUIStyle))]
	[Calls(Type = typeof(GUI), Member = "Box", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000F3")]
	public static void BeginVertical(GUIContent content, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6CB0", Offset = "0x19A5EB0", Length = "0x162")]
	[CalledBy(Type = "Mirror.NetworkClient", Member = "OnGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 9)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "Box", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000E3")]
	public static void Box(string text, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6E20", Offset = "0x19A6020", Length = "0x162")]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Authenticate", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StartButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StopButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomManager", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "DrawPlayerReadyState", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "DrawPlayerReadyButton", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "StopButtons", ReturnType = typeof(void))]
	[CallerCount(Count = 23)]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(GUI), Member = "Button", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Token(Token = "0x60000E5")]
	public static bool Button(string text, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A6F90", Offset = "0x19A6190", Length = "0xED")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "Box", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Token(Token = "0x60000E4")]
	private static void DoBox(GUIContent content, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A7080", Offset = "0x19A6280", Length = "0xED")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "Button", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(bool))]
	[Token(Token = "0x60000E6")]
	private static bool DoButton(GUIContent content, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A7170", Offset = "0x19A6370", Length = "0x146")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUIUtility), Member = "CheckOnGUI", ReturnType = typeof(void))]
	[Calls(Type = typeof(GUI), Member = "DoLabel", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Token(Token = "0x60000E2")]
	private static void DoLabel(GUIContent content, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A72C0", Offset = "0x19A64C0", Length = "0x23A")]
	[CalledBy(Type = typeof(GUILayout), Member = "TextField", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(GUILayoutOption[])}, ReturnType = typeof(string))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIUtility), Member = "GetControlID", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(FocusType)}, ReturnType = typeof(int))]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(GUIUtility), Member = "get_keyboardControl", ReturnType = typeof(int))]
	[Calls(Type = typeof(GUIUtility), Member = "get_compositionString", ReturnType = typeof(string))]
	[Calls(Type = typeof(string), Member = "Concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "DoTextField", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(int), typeof(GUIContent), typeof(bool), typeof(int), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000EA")]
	private static string DoTextField(string text, int maxLength, bool multiline, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A7500", Offset = "0x19A6700", Length = "0x30D")]
	[CalledBy(Type = typeof(GUILayout), Member = "Window", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(Rect), typeof(WindowFunction), typeof(string), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIUtility), Member = "CheckOnGUI", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED960")]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x60000FE")]
	private static Rect DoWindow(int id, Rect screenRect, WindowFunction func, GUIContent content, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A7810", Offset = "0x19A6A10", Length = "0x167")]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Edgegap.EdgegapKcpTransport", Member = "OnGUIRelay", ReturnType = typeof(void))]
	[CalledBy(Type = "kcp2k.KcpTransport", Member = "OnGUIStatistics", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "StopButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "DrawPlayerReadyButton", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "DrawPlayerReadyState", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomManager", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkPingDisplay", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.GUIConsole", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkClient", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "OnGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 13)]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIUtility), Member = "CheckOnGUI", ReturnType = typeof(void))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "EndLayoutArea", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x60000F7")]
	public static void EndArea() { }

	[Address(RVA = "0x19A7980", Offset = "0x19A6B80", Length = "0x40")]
	[CalledBy(Type = "Mirror.NetworkClient", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StartButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StopButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkPingDisplay", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(double), typeof(int), typeof(string), typeof(int), typeof(Color)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Edgegap.EdgegapKcpTransport", Member = "OnGUIRelay", ReturnType = typeof(void))]
	[CallerCount(Count = 10)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "EndLayoutGroup", ReturnType = typeof(void))]
	[Token(Token = "0x60000F1")]
	public static void EndHorizontal() { }

	[Address(RVA = "0x19A79C0", Offset = "0x19A6BC0", Length = "0x6A")]
	[CalledBy(Type = "Mirror.GUIConsole", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "EndLayoutGroup", ReturnType = typeof(void))]
	[Calls(Type = typeof(GUI), Member = "EndScrollView", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Token(Token = "0x60000FB")]
	public static void EndScrollView() { }

	[Address(RVA = "0x19A7A30", Offset = "0x19A6C30", Length = "0x71")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "EndLayoutGroup", ReturnType = typeof(void))]
	[Calls(Type = typeof(GUI), Member = "EndScrollView", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Token(Token = "0x60000FC")]
	internal static void EndScrollView(bool handleScrollWheel) { }

	[Address(RVA = "0x19A7AB0", Offset = "0x19A6CB0", Length = "0x40")]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnClientGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnServerGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Authenticate", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_General", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(double), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Traffic", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(long), typeof(long)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Cpu", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(double), typeof(double), typeof(double), typeof(double), typeof(double)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "OnWindow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "kcp2k.KcpTransport", Member = "OnGUIStatistics", ReturnType = typeof(void))]
	[CallerCount(Count = 11)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "EndLayoutGroup", ReturnType = typeof(void))]
	[Token(Token = "0x60000F4")]
	public static void EndVertical() { }

	[Address(RVA = "0x19A7AF0", Offset = "0x19A6CF0", Length = "0x7F")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000102")]
	public static GUILayoutOption ExpandHeight(bool expand) { }

	[Address(RVA = "0x19A7B70", Offset = "0x19A6D70", Length = "0x7F")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000101")]
	public static GUILayoutOption ExpandWidth(bool expand) { }

	[Address(RVA = "0x19A7BF0", Offset = "0x19A6DF0", Length = "0x4D5")]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(double), typeof(int), typeof(string), typeof(int), typeof(Color)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(float), typeof(float), typeof(float), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED9B0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(GUIStyle), Member = ".ctor", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(GUIUtility), Member = "CheckOnGUI", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[CallsDeduplicatedMethods(Count = 4)]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x60000ED")]
	public static void FlexibleSpace() { }

	[Address(RVA = "0x19A80D0", Offset = "0x19A72D0", Length = "0x8B")]
	[CalledBy(Type = "Mirror.GUIConsole", Member = "OnGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x6000100")]
	public static GUILayoutOption Height(float height) { }

	[Address(RVA = "0x19A8160", Offset = "0x19A7360", Length = "0x17C")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "HorizontalScrollbar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(float), typeof(float), typeof(float), typeof(float), typeof(GUIStyle)}, ReturnType = typeof(float))]
	[Token(Token = "0x60000EC")]
	public static float HorizontalScrollbar(float value, float size, float leftValue, float rightValue, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A82E0", Offset = "0x19A74E0", Length = "0x1E0")]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_ProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(double), typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(double), typeof(int), typeof(string), typeof(int), typeof(Color)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "HorizontalScrollbar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(float), typeof(float), typeof(float), typeof(float), typeof(GUIStyle)}, ReturnType = typeof(float))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000EB")]
	public static float HorizontalScrollbar(float value, float size, float leftValue, float rightValue, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A84D0", Offset = "0x19A76D0", Length = "0x1BB")]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_General", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(double), typeof(int), typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Edgegap.EdgegapKcpTransport", Member = "OnGUIRelay", ReturnType = typeof(void))]
	[CalledBy(Type = "kcp2k.KcpTransport", Member = "OnGUIStatistics", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.Discovery.NetworkDiscoveryHUD", Member = "DrawGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "OnWindow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Cpu", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(double), typeof(double), typeof(double), typeof(double), typeof(double)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Traffic", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(long), typeof(long)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Authenticate", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(double), typeof(int), typeof(string), typeof(int), typeof(Color)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnClientGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkRoomPlayer", Member = "DrawPlayerReadyState", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkPingDisplay", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.GUIConsole", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StatusLabels", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StartButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkClient", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.NetworkStatistics", Member = "OnServerGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 51)]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUIUtility), Member = "CheckOnGUI", ReturnType = typeof(void))]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(GUI), Member = "DoLabel", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(GUIStyle)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Token(Token = "0x60000E1")]
	public static void Label(string text, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A8840", Offset = "0x19A7A40", Length = "0x163")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUI), Member = "PasswordFieldGetStrToShow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(char)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "PasswordField", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(string), typeof(char), typeof(int), typeof(GUIStyle)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000E9")]
	public static string PasswordField(string password, char maskChar, int maxLength, GUIStyle style, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A8690", Offset = "0x19A7890", Length = "0x1A2")]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUI_Authenticate", ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUI), Member = "PasswordFieldGetStrToShow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(char)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(GUILayoutUtility), Member = "DoGetRect", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "PasswordField", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(string), typeof(char), typeof(int), typeof(GUIStyle)}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000E8")]
	public static string PasswordField(string password, char maskChar, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A89B0", Offset = "0x19A7BB0", Length = "0x7F")]
	[CalledBy(Type = "Mirror.NetworkManagerHUD", Member = "StartButtons", ReturnType = typeof(void))]
	[CalledBy(Type = "Edgegap.EdgegapKcpTransport", Member = "OnGUIRelay", ReturnType = typeof(void))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUILayout), Member = "DoTextField", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(int), typeof(bool), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(string))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000E7")]
	public static string TextField(string text, GUILayoutOption[] options) { }

	[Address(RVA = "0x19A8A30", Offset = "0x19A7C30", Length = "0x8B")]
	[CalledBy(Type = "Mirror.GUIConsole", Member = "OnGUI", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_ProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(double), typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "GUILayout_TextAndProgressBar", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(double), typeof(int), typeof(string), typeof(int), typeof(Color)}, ReturnType = typeof(void))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_value_box")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[CallsDeduplicatedMethods(Count = 1)]
	[Token(Token = "0x60000FF")]
	public static GUILayoutOption Width(float width) { }

	[Address(RVA = "0x19A8AC0", Offset = "0x19A7CC0", Length = "0x107")]
	[CalledBy(Type = "Mirror.RemoteStatistics", Member = "OnGUI", ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUIContent), Member = "Temp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(GUIContent))]
	[Calls(Type = typeof(GUI), Member = "get_skin", ReturnType = typeof(GUISkin))]
	[Calls(Type = typeof(GUILayout), Member = "DoWindow", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(Rect), typeof(WindowFunction), typeof(GUIContent), typeof(GUIStyle), typeof(GUILayoutOption[])}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x60000FD")]
	public static Rect Window(int id, Rect screenRect, WindowFunction func, string text, GUILayoutOption[] options) { }

}

