namespace UnityEngine;

[Token(Token = "0x200002D")]
internal struct SliderHandler
{
	[FieldOffset(Offset = "0x0")]
	[Token(Token = "0x4000113")]
	private readonly Rect position; //Field offset: 0x0
	[FieldOffset(Offset = "0x10")]
	[Token(Token = "0x4000114")]
	private readonly float currentValue; //Field offset: 0x10
	[FieldOffset(Offset = "0x14")]
	[Token(Token = "0x4000115")]
	private readonly float size; //Field offset: 0x14
	[FieldOffset(Offset = "0x18")]
	[Token(Token = "0x4000116")]
	private readonly float start; //Field offset: 0x18
	[FieldOffset(Offset = "0x1C")]
	[Token(Token = "0x4000117")]
	private readonly float end; //Field offset: 0x1C
	[FieldOffset(Offset = "0x20")]
	[Token(Token = "0x4000118")]
	private readonly GUIStyle slider; //Field offset: 0x20
	[FieldOffset(Offset = "0x28")]
	[Token(Token = "0x4000119")]
	private readonly GUIStyle thumb; //Field offset: 0x28
	[FieldOffset(Offset = "0x30")]
	[Token(Token = "0x400011A")]
	private readonly GUIStyle thumbExtent; //Field offset: 0x30
	[FieldOffset(Offset = "0x38")]
	[Token(Token = "0x400011B")]
	private readonly bool horiz; //Field offset: 0x38
	[FieldOffset(Offset = "0x3C")]
	[Token(Token = "0x400011C")]
	private readonly int id; //Field offset: 0x3C

	[Address(RVA = "0x19C48A0", Offset = "0x19C3AA0", Length = "0x7D")]
	[CalledBy(Type = typeof(GUI), Member = "Slider", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(float), typeof(float), typeof(float), typeof(float), typeof(GUIStyle), typeof(GUIStyle), typeof(bool), typeof(int), typeof(GUIStyle)}, ReturnType = typeof(float))]
	[CalledBy(Type = typeof(GUI), Member = "Scroller", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(float), typeof(float), typeof(float), typeof(float), typeof(GUIStyle), typeof(GUIStyle), typeof(GUIStyle), typeof(GUIStyle), typeof(bool)}, ReturnType = typeof(float))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Token(Token = "0x6000275")]
	public SliderHandler(Rect position, float currentValue, float size, float start, float end, GUIStyle slider, GUIStyle thumb, bool horiz, int id, GUIStyle thumbExtent = null) { }

	[Address(RVA = "0x19C2D30", Offset = "0x19C1F30", Length = "0x27")]
	[CallerCount(Count = 0)]
	[Token(Token = "0x6000283")]
	private float Clamp(float value) { }

	[Address(RVA = "0x19C2D60", Offset = "0x19C1F60", Length = "0x2C")]
	[CallerCount(Count = 0)]
	[Token(Token = "0x600028B")]
	private float ClampedCurrentValue() { }

	[Address(RVA = "0x19C2DC0", Offset = "0x19C1FC0", Length = "0x9")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Token(Token = "0x6000281")]
	private Event CurrentEvent() { }

	[Address(RVA = "0x19C2D90", Offset = "0x19C1F90", Length = "0x2D")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(Event), Member = "GetTypeForControl", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(EventType))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x600027B")]
	private EventType CurrentEventType() { }

	[Address(RVA = "0x19C2DD0", Offset = "0x19C1FD0", Length = "0x9F")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(Event), Member = "get_mousePosition", ReturnType = typeof(Vector2))]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x600027C")]
	private int CurrentScrollTroughSide() { }

	[Address(RVA = "0x19C2E70", Offset = "0x19C2070", Length = "0xA6")]
	[CalledBy(Type = typeof(GUI), Member = "Slider", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(float), typeof(float), typeof(float), typeof(float), typeof(GUIStyle), typeof(GUIStyle), typeof(bool), typeof(int), typeof(GUIStyle)}, ReturnType = typeof(float))]
	[CalledBy(Type = typeof(GUI), Member = "Scroller", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(float), typeof(float), typeof(float), typeof(float), typeof(GUIStyle), typeof(GUIStyle), typeof(GUIStyle), typeof(GUIStyle), typeof(bool)}, ReturnType = typeof(float))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(Event), Member = "GetTypeForControl", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(EventType))]
	[Calls(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "OnMouseDrag", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "OnMouseUp", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000276")]
	public float Handle() { }

	[Address(RVA = "0x19C2F20", Offset = "0x19C2120", Length = "0x1D3")]
	[CalledBy(Type = typeof(SliderHandler), Member = "ThumbSelectionRect", ReturnType = typeof(Rect))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "CurrentScrollTroughSide", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(SliderHandler), Member = "PageMovementValue", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "PageUpMovementBound", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ValueForCurrentMousePosition", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ThumbExtRect", ReturnType = typeof(Rect))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ThumbRect", ReturnType = typeof(Rect))]
	[CallerCount(Count = 11)]
	[Calls(Type = typeof(SliderHandler), Member = "ThumbSize", ReturnType = typeof(float))]
	[Calls(Type = typeof(GUIStyle), Member = "get_fixedHeight", ReturnType = typeof(float))]
	[Calls(Type = typeof(RectOffset), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect)}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(GUIStyle), Member = "get_margin", ReturnType = typeof(RectOffset))]
	[Calls(Type = typeof(SliderHandler), Member = "ValuesPerPixel", ReturnType = typeof(float))]
	[Calls(Type = typeof(GUIStyle), Member = "get_padding", ReturnType = typeof(RectOffset))]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600028A")]
	private Rect HorizontalThumbRect() { }

	[Address(RVA = "0x19C3100", Offset = "0x19C2300", Length = "0x13")]
	[CallerCount(Count = 0)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600027D")]
	private bool IsEmptySlider() { }

	[Address(RVA = "0x19C3120", Offset = "0x19C2320", Length = "0x12")]
	[CallerCount(Count = 0)]
	[Token(Token = "0x600028F")]
	private float MaxValue() { }

	[Address(RVA = "0x19C3140", Offset = "0x19C2340", Length = "0xD")]
	[CallerCount(Count = 0)]
	[Token(Token = "0x6000290")]
	private float MinValue() { }

	[Address(RVA = "0x19C3150", Offset = "0x19C2350", Length = "0x74")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDrag", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "PageMovementValue", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ValueForCurrentMousePosition", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "StartDraggingWithValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(Event), Member = "get_mousePosition", ReturnType = typeof(Vector2))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x600028C")]
	private float MousePosition() { }

	[Address(RVA = "0x19C31D0", Offset = "0x19C23D0", Length = "0x501")]
	[CalledBy(Type = typeof(SliderHandler), Member = "Handle", ReturnType = typeof(float))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(Event), Member = "Use", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1819BAAF0")]
	[Calls(Type = typeof(SliderHandler), Member = "CurrentScrollTroughSide", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18199CE00")]
	[Calls(Type = typeof(DateTime), Member = "AddMilliseconds", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(double)}, ReturnType = typeof(DateTime))]
	[Calls(Type = "UnityEngine.SystemClock", Member = "get_now", ReturnType = typeof(DateTime))]
	[Calls(Type = typeof(SliderHandler), Member = "SliderState", ReturnType = typeof(SliderState))]
	[Calls(Type = typeof(SliderHandler), Member = "StartDraggingWithValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(SliderHandler), Member = "ValueForCurrentMousePosition", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "SupportsPageMovements", ReturnType = typeof(bool))]
	[Calls(Type = typeof(GUI), Member = "set_changed", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(SliderHandler), Member = "PageMovementValue", ReturnType = typeof(float))]
	[Calls(Type = typeof(Math), Member = "Max", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(float)}, ReturnType = typeof(float))]
	[Calls(Type = typeof(Math), Member = "Min", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(float)}, ReturnType = typeof(float))]
	[Calls(Type = typeof(GUIUtility), Member = "HitTest", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(Event)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(SliderHandler), Member = "MousePosition", ReturnType = typeof(float))]
	[CallsDeduplicatedMethods(Count = 1)]
	[CallsUnknownMethods(Count = 1)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000277")]
	private float OnMouseDown() { }

	[Address(RVA = "0x19C36E0", Offset = "0x19C28E0", Length = "0x186")]
	[CalledBy(Type = typeof(SliderHandler), Member = "Handle", ReturnType = typeof(float))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(SliderHandler), Member = "SliderState", ReturnType = typeof(SliderState))]
	[Calls(Type = typeof(GUI), Member = "set_changed", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(Event), Member = "Use", ReturnType = typeof(void))]
	[Calls(Type = typeof(SliderHandler), Member = "MousePosition", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "ValuesPerPixel", ReturnType = typeof(float))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000278")]
	private float OnMouseDrag() { }

	[Address(RVA = "0x19C3870", Offset = "0x19C2A70", Length = "0x120")]
	[CalledBy(Type = typeof(SliderHandler), Member = "Handle", ReturnType = typeof(float))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(Event), Member = "Use", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 2)]
	[Token(Token = "0x6000279")]
	private float OnMouseUp() { }

	[Address(RVA = "0x19C39A0", Offset = "0x19C2BA0", Length = "0x5EA")]
	[CalledBy(Type = typeof(SliderHandler), Member = "Handle", ReturnType = typeof(float))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(SliderHandler), Member = "SliderState", ReturnType = typeof(SliderState))]
	[Calls(Type = typeof(SliderHandler), Member = "SupportsPageMovements", ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x18199CE00")]
	[Calls(Type = typeof(DateTime), Member = "AddMilliseconds", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(double)}, ReturnType = typeof(DateTime))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1819BAAA0")]
	[Calls(Type = typeof(SliderHandler), Member = "CurrentScrollTroughSide", ReturnType = typeof(int))]
	[Calls(Type = typeof(DateTime), Member = "op_LessThan", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DateTime), typeof(DateTime)}, ReturnType = typeof(bool))]
	[Calls(Type = "UnityEngine.SystemClock", Member = "get_now", ReturnType = typeof(DateTime))]
	[Calls(Type = typeof(GUI), Member = "InternalRepaintEditorWindow", ReturnType = typeof(void))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUI), Member = "set_changed", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "ThumbExtRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(GUIStyle), Member = "Draw", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(GUIContent), typeof(int), typeof(bool), typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(GUIUtility), Member = "HitTest", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect), typeof(Event)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(GUIUtility), Member = "set_hotControl", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(SliderHandler), Member = "PageMovementValue", ReturnType = typeof(float))]
	[CallsUnknownMethods(Count = 1)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600027A")]
	private float OnRepaint() { }

	[Address(RVA = "0x19C3F90", Offset = "0x19C3190", Length = "0x101")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(SliderHandler), Member = "MousePosition", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Token(Token = "0x600027F")]
	private float PageMovementValue() { }

	[Address(RVA = "0x19C40A0", Offset = "0x19C32A0", Length = "0x5C")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Token(Token = "0x6000280")]
	private float PageUpMovementBound() { }

	[Address(RVA = "0x19C4100", Offset = "0x19C3300", Length = "0x107")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDrag", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "StartDraggingWithValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Type), Member = "GetTypeFromHandle", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(RuntimeTypeHandle)}, ReturnType = typeof(Type))]
	[Calls(Type = typeof(GUIStateObjects), Member = "GetStateObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(int)}, ReturnType = typeof(object))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Token(Token = "0x6000286")]
	private SliderState SliderState() { }

	[Address(RVA = "0x19C4210", Offset = "0x19C3410", Length = "0x51")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(SliderHandler), Member = "SliderState", ReturnType = typeof(SliderState))]
	[Calls(Type = typeof(SliderHandler), Member = "MousePosition", ReturnType = typeof(float))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000285")]
	private void StartDraggingWithValue(float dragStartValue) { }

	[Address(RVA = "0x19C4270", Offset = "0x19C3470", Length = "0x5E")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(GUI), Member = "get_usePageScrollbars", ReturnType = typeof(bool))]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600027E")]
	private bool SupportsPageMovements() { }

	[Address(RVA = "0x19C42D0", Offset = "0x19C34D0", Length = "0xEA")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(GUIStyle), Member = "get_fixedWidth", ReturnType = typeof(float))]
	[Calls(Type = typeof(GUIStyle), Member = "get_fixedHeight", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000287")]
	private Rect ThumbExtRect() { }

	[Address(RVA = "0x19C43C0", Offset = "0x19C35C0", Length = "0x45")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[DeduplicatedMethod]
	[Token(Token = "0x6000288")]
	private Rect ThumbRect() { }

	[Address(RVA = "0x19C43C0", Offset = "0x19C35C0", Length = "0x45")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[DeduplicatedMethod]
	[Token(Token = "0x6000284")]
	private Rect ThumbSelectionRect() { }

	[Address(RVA = "0x19C4410", Offset = "0x19C3610", Length = "0xB6")]
	[CalledBy(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[CalledBy(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ValuesPerPixel", ReturnType = typeof(float))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(GUIStyle), Member = "get_fixedHeight", ReturnType = typeof(float))]
	[Calls(Type = typeof(GUIStyle), Member = "get_padding", ReturnType = typeof(RectOffset))]
	[Calls(Type = typeof(RectOffset), Member = "get_vertical", ReturnType = typeof(int))]
	[Calls(Type = typeof(GUIStyle), Member = "get_fixedWidth", ReturnType = typeof(float))]
	[Calls(Type = typeof(RectOffset), Member = "get_horizontal", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600028E")]
	private float ThumbSize() { }

	[Address(RVA = "0x19C44D0", Offset = "0x19C36D0", Length = "0x124")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(Event), Member = "get_current", ReturnType = typeof(Event))]
	[Calls(Type = typeof(Event), Member = "get_mousePosition", ReturnType = typeof(Vector2))]
	[Calls(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[Calls(Type = typeof(SliderHandler), Member = "ValuesPerPixel", ReturnType = typeof(float))]
	[Calls(Type = typeof(SliderHandler), Member = "MousePosition", ReturnType = typeof(float))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000282")]
	private float ValueForCurrentMousePosition() { }

	[Address(RVA = "0x19C4600", Offset = "0x19C3800", Length = "0xB4")]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDrag", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ValueForCurrentMousePosition", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "VerticalThumbRect", ReturnType = typeof(Rect))]
	[CalledBy(Type = typeof(SliderHandler), Member = "HorizontalThumbRect", ReturnType = typeof(Rect))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(GUIStyle), Member = "get_padding", ReturnType = typeof(RectOffset))]
	[Calls(Type = typeof(RectOffset), Member = "get_vertical", ReturnType = typeof(int))]
	[Calls(Type = typeof(RectOffset), Member = "get_horizontal", ReturnType = typeof(int))]
	[Calls(Type = typeof(SliderHandler), Member = "ThumbSize", ReturnType = typeof(float))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600028D")]
	private float ValuesPerPixel() { }

	[Address(RVA = "0x19C46C0", Offset = "0x19C38C0", Length = "0x1D6")]
	[CalledBy(Type = typeof(SliderHandler), Member = "ThumbSelectionRect", ReturnType = typeof(Rect))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnMouseDown", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "OnRepaint", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "CurrentScrollTroughSide", ReturnType = typeof(int))]
	[CalledBy(Type = typeof(SliderHandler), Member = "PageMovementValue", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "PageUpMovementBound", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ValueForCurrentMousePosition", ReturnType = typeof(float))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ThumbExtRect", ReturnType = typeof(Rect))]
	[CalledBy(Type = typeof(SliderHandler), Member = "ThumbRect", ReturnType = typeof(Rect))]
	[CallerCount(Count = 11)]
	[Calls(Type = typeof(SliderHandler), Member = "ThumbSize", ReturnType = typeof(float))]
	[Calls(Type = typeof(GUIStyle), Member = "get_fixedWidth", ReturnType = typeof(float))]
	[Calls(Type = typeof(RectOffset), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Rect)}, ReturnType = typeof(Rect))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(GUIStyle), Member = "get_margin", ReturnType = typeof(RectOffset))]
	[Calls(Type = typeof(SliderHandler), Member = "ValuesPerPixel", ReturnType = typeof(float))]
	[Calls(Type = typeof(GUIStyle), Member = "get_padding", ReturnType = typeof(RectOffset))]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000289")]
	private Rect VerticalThumbRect() { }

}

