namespace MoonSharp.Interpreter;

[DefaultMember("Item")]
[Token(Token = "0x2000052")]
public class Table : RefIdObject, IScriptPrivateResource
{
	[CompilerGenerated]
	[Token(Token = "0x2000053")]
	private sealed class <>c
	{
		[Token(Token = "0x40001FA")]
		public static readonly <>c <>9; //Field offset: 0x0
		[Token(Token = "0x40001FB")]
		public static Func<TablePair, TablePair> <>9__56_0; //Field offset: 0x8
		[Token(Token = "0x40001FC")]
		public static Func<TablePair, DynValue> <>9__58_0; //Field offset: 0x10
		[Token(Token = "0x40001FD")]
		public static Func<TablePair, DynValue> <>9__60_0; //Field offset: 0x18

		[Address(RVA = "0x314400", Offset = "0x313600", Length = "0x67")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[CallsDeduplicatedMethods(Count = 1)]
		[Token(Token = "0x6000571")]
		private static <>c() { }

		[Address(RVA = "0x2BC7B0", Offset = "0x2BB9B0", Length = "0x7")]
		[CallerCount(Count = 2609)]
		[CallsDeduplicatedMethods(Count = 1)]
		[DeduplicatedMethod]
		[Token(Token = "0x6000572")]
		public <>c() { }

		[Address(RVA = "0x313FD0", Offset = "0x3131D0", Length = "0x43")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Token(Token = "0x6000574")]
		internal DynValue <get_Keys>b__58_0(TablePair n) { }

		[Address(RVA = "0x314020", Offset = "0x313220", Length = "0x76")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Token(Token = "0x6000573")]
		internal TablePair <get_Pairs>b__56_0(TablePair n) { }

		[Address(RVA = "0x3140A0", Offset = "0x3132A0", Length = "0x44")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Token(Token = "0x6000575")]
		internal DynValue <get_Values>b__60_0(TablePair n) { }

	}

	[FieldOffset(Offset = "0x18")]
	[Token(Token = "0x40001F1")]
	private readonly LinkedList<TablePair> m_Values; //Field offset: 0x18
	[FieldOffset(Offset = "0x20")]
	[Token(Token = "0x40001F2")]
	private readonly LinkedListIndex<DynValue, TablePair> m_ValueMap; //Field offset: 0x20
	[FieldOffset(Offset = "0x28")]
	[Token(Token = "0x40001F3")]
	private readonly LinkedListIndex<String, TablePair> m_StringMap; //Field offset: 0x28
	[FieldOffset(Offset = "0x30")]
	[Token(Token = "0x40001F4")]
	private readonly LinkedListIndex<Int32, TablePair> m_ArrayMap; //Field offset: 0x30
	[FieldOffset(Offset = "0x38")]
	[Token(Token = "0x40001F5")]
	private readonly Script m_Owner; //Field offset: 0x38
	[FieldOffset(Offset = "0x40")]
	[Token(Token = "0x40001F6")]
	private int m_InitArray; //Field offset: 0x40
	[FieldOffset(Offset = "0x44")]
	[Token(Token = "0x40001F7")]
	private int m_CachedLength; //Field offset: 0x44
	[FieldOffset(Offset = "0x48")]
	[Token(Token = "0x40001F8")]
	private bool m_ContainsNilEntries; //Field offset: 0x48
	[FieldOffset(Offset = "0x50")]
	[Token(Token = "0x40001F9")]
	private Table m_MetaTable; //Field offset: 0x50

	[Token(Token = "0x170000AD")]
	public object Item
	{
		[Address(RVA = "0x312940", Offset = "0x311B40", Length = "0x24")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
		[Calls(Type = typeof(ScriptToClrConversions), Member = "DynValueToObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(object))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Token(Token = "0x600054A")]
		 get { } //Length: 36
		[Address(RVA = "0x312EB0", Offset = "0x3120B0", Length = "0x1DD")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
		[Calls(Type = typeof(Table), Member = "ResolveMultipleKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(Object&)}, ReturnType = typeof(Table))]
		[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(DynValue)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
		[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(DynValue)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DynValue)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(ScriptRuntimeException), Member = "TableIndexIsNil", ReturnType = typeof(ScriptRuntimeException))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Token(Token = "0x600054B")]
		 set { } //Length: 477
	}

	[Token(Token = "0x170000AE")]
	public object Item
	{
		[Address(RVA = "0x312970", Offset = "0x311B70", Length = "0xB4")]
		[CalledBy(Type = "Polytoria.Datamodel.BaseScript", Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(object))]
		[CallerCount(Count = 1)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(ScriptToClrConversions), Member = "DynValueToObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(object))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Token(Token = "0x600054C")]
		 get { } //Length: 180
		[Address(RVA = "0x313090", Offset = "0x312290", Length = "0x85")]
		[CalledBy(Type = "Polytoria.Datamodel.BaseScript", Member = "set_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Services.ScriptService+<RunScriptInstance>d__13", Member = "MoveNext", ReturnType = typeof(bool))]
		[CalledBy(Type = typeof(TableConversions), Member = "ConvertIListToTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(IList)}, ReturnType = typeof(Table))]
		[CalledBy(Type = typeof(LoadModule), Member = "MoonSharpInit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Table)}, ReturnType = typeof(void))]
		[CallerCount(Count = 47)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
		[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(DynValue)}, ReturnType = typeof(void))]
		[Token(Token = "0x600054D")]
		 set { } //Length: 133
	}

	[Token(Token = "0x170000B2")]
	public IEnumerable<DynValue> Keys
	{
		[Address(RVA = "0x312A30", Offset = "0x311C30", Length = "0x111")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
		[Calls(Type = typeof(Func`2), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(IntPtr)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(Enumerable), Member = "Select", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"TSource", "TResult"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Collections.Generic.IEnumerable`1<TSource>", "System.Func`2<TSource, TResult>"}, ReturnType = "System.Collections.Generic.IEnumerable`1<TResult>")]
		[Token(Token = "0x600056F")]
		 get { } //Length: 273
	}

	[Token(Token = "0x170000AF")]
	public int Length
	{
		[Address(RVA = "0x312B50", Offset = "0x311D50", Length = "0x112")]
		[CalledBy(Type = typeof(TableConversions), Member = "TableToList", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), "System.Func`2<DynValue, T>"}, ReturnType = "System.Collections.Generic.List`1<T>")]
		[CalledBy(Type = typeof(DynValue), Member = "GetLength", ReturnType = typeof(DynValue))]
		[CalledBy(Type = typeof(Table), Member = "Append", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(JsonTableConverter), Member = "TableToJson", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(StringBuilder), typeof(Table)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToArrayOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
		[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToListOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
		[CalledBy(Type = typeof(Processor), Member = "ExecLen", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction), typeof(int)}, ReturnType = typeof(int))]
		[CalledBy(Type = typeof(TableModule), Member = "GetTableLength", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(DynValue)}, ReturnType = typeof(int))]
		[CallerCount(Count = 11)]
		[Calls(Type = typeof(LinkedListIndex`2), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = "System.Collections.Generic.LinkedListNode`1<TValue>")]
		[Calls(Type = typeof(LinkedListIndex`2), Member = "ContainsKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = typeof(bool))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[ContainsUnimplementedInstructions]
		[Token(Token = "0x600056A")]
		 get { } //Length: 274
	}

	[Token(Token = "0x170000B0")]
	public Table MetaTable
	{
		[Address(RVA = "0x2DD2B0", Offset = "0x2DC4B0", Length = "0x5")]
		[CallerCount(Count = 8)]
		[DeduplicatedMethod]
		[Token(Token = "0x600056C")]
		 get { } //Length: 5
		[Address(RVA = "0x313120", Offset = "0x312320", Length = "0x36")]
		[CalledBy(Type = typeof(DebugModule), Member = "setmetatable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
		[CalledBy(Type = typeof(IoModule), Member = "MoonSharpInit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Table)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(MetaTableModule), Member = "setmetatable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
		[CallerCount(Count = 3)]
		[Calls(Type = typeof(ScriptPrivateResource_Extension), Member = "CheckScriptOwnership", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IScriptPrivateResource), typeof(IScriptPrivateResource)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Token(Token = "0x600056D")]
		 set { } //Length: 54
	}

	[Token(Token = "0x170000AC")]
	public override Script OwnerScript
	{
		[Address(RVA = "0x309610", Offset = "0x308810", Length = "0x5")]
		[CallerCount(Count = 16)]
		[DeduplicatedMethod]
		[Token(Token = "0x6000547")]
		 get { } //Length: 5
	}

	[Token(Token = "0x170000B1")]
	public IEnumerable<TablePair> Pairs
	{
		[Address(RVA = "0x312C70", Offset = "0x311E70", Length = "0x111")]
		[CalledBy(Type = "Polytoria.Datamodel.Services.HttpService+<DoRequest>d__11", Member = "MoveNext", ReturnType = typeof(bool))]
		[CalledBy(Type = typeof(SerializationExtensions), Member = "Serialize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(bool), typeof(int)}, ReturnType = typeof(string))]
		[CalledBy(Type = typeof(JsonTableConverter), Member = "TableToJson", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(StringBuilder), typeof(Table)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(PropertyTableAssigner), Member = "AssignObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(Table)}, ReturnType = typeof(void))]
		[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToDictionaryOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
		[CalledBy(Type = typeof(TableConversions), Member = "TableToDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"TK", "TV"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), "System.Func`2<DynValue, TK>", "System.Func`2<DynValue, TV>"}, ReturnType = "System.Collections.Generic.Dictionary`2<TK, TV>")]
		[CallerCount(Count = 6)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
		[Calls(Type = typeof(Func`2), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(IntPtr)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(Enumerable), Member = "Select", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TablePair), typeof(TablePair)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(System.Collections.Generic.IEnumerable`1<MoonSharp.Interpreter.TablePair>), typeof(System.Func`2<MoonSharp.Interpreter.TablePair, MoonSharp.Interpreter.TablePair>)}, ReturnType = typeof(System.Collections.Generic.IEnumerable`1<MoonSharp.Interpreter.TablePair>))]
		[Token(Token = "0x600056E")]
		 get { } //Length: 273
	}

	[Token(Token = "0x170000B3")]
	public IEnumerable<DynValue> Values
	{
		[Address(RVA = "0x312D90", Offset = "0x311F90", Length = "0x111")]
		[CalledBy(Type = typeof(SerializationExtensions), Member = "Serialize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(bool), typeof(int)}, ReturnType = typeof(string))]
		[CalledBy(Type = typeof(EnumerableWrapper), Member = "ConvertTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table)}, ReturnType = typeof(DynValue))]
		[CallerCount(Count = 3)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
		[Calls(Type = typeof(Func`2), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(IntPtr)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
		[Calls(Type = typeof(Enumerable), Member = "Select", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"TSource", "TResult"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Collections.Generic.IEnumerable`1<TSource>", "System.Func`2<TSource, TResult>"}, ReturnType = "System.Collections.Generic.IEnumerable`1<TResult>")]
		[Token(Token = "0x6000570")]
		 get { } //Length: 273
	}

	[Address(RVA = "0x3126B0", Offset = "0x3118B0", Length = "0x1BF")]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertIListToTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(IList)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(TableModule_Globals), Member = "pack", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "pack", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(StringModule), Member = "MoonSharpInit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(OsTimeModule), Member = "date", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(IoModule), Member = "MoonSharpInit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertIDictionaryToTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(IDictionary)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(JsonTableConverter), Member = "ParseJsonArray", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Lexer), typeof(Script)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(JsonTableConverter), Member = "ParseJsonObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Lexer), typeof(Script)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(Script), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(CoreModules)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ModuleRegister), Member = "CreateModuleNamespace", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Type)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(Table), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(DynValue[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DynValue), Member = "NewTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(DynValue[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(DynValue), Member = "NewTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(DynValue), Member = "NewPrimeTable", ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(ObjectValueConverter), Member = "SerializeObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object), typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 17)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[CallsDeduplicatedMethods(Count = 5)]
	[Token(Token = "0x6000545")]
	public Table(Script owner) { }

	[Address(RVA = "0x312870", Offset = "0x311A70", Length = "0xC0")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(DynValue), Member = "NewNumber", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(double)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000546")]
	public Table(Script owner, DynValue[] arrayValues) { }

	[Address(RVA = "0x3105F0", Offset = "0x30F7F0", Length = "0x126")]
	[CalledBy(Type = typeof(ObjectValueConverter), Member = "SerializeObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object), typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(JsonTableConverter), Member = "ParseJsonArray", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Lexer), typeof(Script)}, ReturnType = typeof(Table))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(ScriptPrivateResource_Extension), Member = "CheckScriptOwnership", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IScriptPrivateResource), typeof(IScriptPrivateResource)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Table), Member = "get_Length", ReturnType = typeof(int))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(DynValue), Member = "NewNumber", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(double)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "PerformTableSet", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<T, TablePair>", "T", typeof(DynValue), typeof(DynValue), typeof(bool), typeof(int)}, ReturnType = typeof(void))]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600054F")]
	public void Append(DynValue value) { }

	[Address(RVA = "0x310720", Offset = "0x30F920", Length = "0xAF")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LinkedList`1), Member = "Clear", ReturnType = typeof(void))]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "Clear", ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000548")]
	public void Clear() { }

	[Address(RVA = "0x3107D0", Offset = "0x30F9D0", Length = "0x117")]
	[CalledBy(Type = typeof(Table), Member = "PerformTableSet", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<T, TablePair>", "T", typeof(DynValue), typeof(DynValue), typeof(bool), typeof(int)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(LinkedListNode`1), Member = "get_Next", ReturnType = "System.Collections.Generic.LinkedListNode`1<T>")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000567")]
	public void CollectDeadKeys() { }

	[Address(RVA = "0x310BD0", Offset = "0x30FDD0", Length = "0xA1")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Token(Token = "0x6000559")]
	public DynValue Get(object key) { }

	[Address(RVA = "0x310B20", Offset = "0x30FD20", Length = "0xA1")]
	[CalledBy(Type = typeof(IndexExpression), Member = "Eval", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(LuaBase), Member = "LuaGetTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(LuaState), typeof(int)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Processor), Member = "ExecIndexSet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(Processor), Member = "ExecIndex", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(MetaTableModule), Member = "rawget", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Token(Token = "0x6000558")]
	public DynValue Get(DynValue key) { }

	[Address(RVA = "0x310E50", Offset = "0x310050", Length = "0x9F")]
	[CalledBy(Type = typeof(TableModule), Member = "unpack", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(JsonTableConverter), Member = "TableToJson", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(StringBuilder), typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DynValueMemberDescriptor), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(string)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToArrayOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToListOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(TableConversions), Member = "TableToList", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), "System.Func`2<DynValue, T>"}, ReturnType = "System.Collections.Generic.List`1<T>")]
	[CalledBy(Type = typeof(TableIteratorsModule), Member = "__next_i", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "sort", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "insert", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "concat", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 12)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DynValue))]
	[Token(Token = "0x6000557")]
	public DynValue Get(int key) { }

	[Address(RVA = "0x310EF0", Offset = "0x3100F0", Length = "0xA1")]
	[CalledBy(Type = typeof(IoModule), Member = "GetDefaultFile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(StandardFileType)}, ReturnType = typeof(FileUserDataBase))]
	[CalledBy(Type = "Polytoria.Datamodel.BaseScript", Member = "Call", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), "System.Object[]"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.BaseScript", Member = "Update", ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.BaseScript", Member = "FixedUpdate", ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Processor), Member = "GetGenericSymbol", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(SymbolRef)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Processor), Member = "GetGlobalSymbol", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(string)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(IoModule), Member = "__index_callback", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(IoModule), Member = "GetStandardFile", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(StandardFileType)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(LoadModule), Member = "MoonSharpInit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(MathModule), Member = "GetRandom", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script)}, ReturnType = typeof(Random))]
	[CalledBy(Type = typeof(MathModule), Member = "random", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(MetaTableModule), Member = "getmetatable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(OsTimeModule), Member = "GetTimeTableField", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(string)}, ReturnType = typeof(System.Nullable`1<System.Int32>))]
	[CallerCount(Count = 13)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Token(Token = "0x6000556")]
	public DynValue Get(string key) { }

	[Address(RVA = "0x310C80", Offset = "0x30FE80", Length = "0x1C1")]
	[CalledBy(Type = typeof(Table), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(object))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "ResolveMultipleKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(Object&)}, ReturnType = typeof(Table))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Token(Token = "0x600055A")]
	public DynValue Get(Object[] keys) { }

	[Address(RVA = "0x312970", Offset = "0x311B70", Length = "0xB4")]
	[CalledBy(Type = "Polytoria.Datamodel.BaseScript", Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(object))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ScriptToClrConversions), Member = "DynValueToObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(object))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x600054C")]
	public object get_Item(object key) { }

	[Address(RVA = "0x312940", Offset = "0x311B40", Length = "0x24")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(ScriptToClrConversions), Member = "DynValueToObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(object))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x600054A")]
	public object get_Item(Object[] keys) { }

	[Address(RVA = "0x312A30", Offset = "0x311C30", Length = "0x111")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(Func`2), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(IntPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(Enumerable), Member = "Select", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"TSource", "TResult"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Collections.Generic.IEnumerable`1<TSource>", "System.Func`2<TSource, TResult>"}, ReturnType = "System.Collections.Generic.IEnumerable`1<TResult>")]
	[Token(Token = "0x600056F")]
	public IEnumerable<DynValue> get_Keys() { }

	[Address(RVA = "0x312B50", Offset = "0x311D50", Length = "0x112")]
	[CalledBy(Type = typeof(Processor), Member = "ExecLen", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToListOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToArrayOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(TableModule), Member = "GetTableLength", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(DynValue)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(Table), Member = "Append", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DynValue), Member = "GetLength", ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableConversions), Member = "TableToList", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), "System.Func`2<DynValue, T>"}, ReturnType = "System.Collections.Generic.List`1<T>")]
	[CalledBy(Type = typeof(JsonTableConverter), Member = "TableToJson", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(StringBuilder), typeof(Table)}, ReturnType = typeof(void))]
	[CallerCount(Count = 11)]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = "System.Collections.Generic.LinkedListNode`1<TValue>")]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "ContainsKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600056A")]
	public int get_Length() { }

	[Address(RVA = "0x2DD2B0", Offset = "0x2DC4B0", Length = "0x5")]
	[CallerCount(Count = 8)]
	[DeduplicatedMethod]
	[Token(Token = "0x600056C")]
	public Table get_MetaTable() { }

	[Address(RVA = "0x309610", Offset = "0x308810", Length = "0x5")]
	[CallerCount(Count = 16)]
	[DeduplicatedMethod]
	[Token(Token = "0x6000547")]
	public override Script get_OwnerScript() { }

	[Address(RVA = "0x312C70", Offset = "0x311E70", Length = "0x111")]
	[CalledBy(Type = "Polytoria.Datamodel.Services.HttpService+<DoRequest>d__11", Member = "MoveNext", ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(SerializationExtensions), Member = "Serialize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(bool), typeof(int)}, ReturnType = typeof(string))]
	[CalledBy(Type = typeof(JsonTableConverter), Member = "TableToJson", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(StringBuilder), typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(PropertyTableAssigner), Member = "AssignObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertTableToDictionaryOfGenericType", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Type), typeof(Type), typeof(Type), typeof(Table)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(TableConversions), Member = "TableToDictionary", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"TK", "TV"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), "System.Func`2<DynValue, TK>", "System.Func`2<DynValue, TV>"}, ReturnType = "System.Collections.Generic.Dictionary`2<TK, TV>")]
	[CallerCount(Count = 6)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(Func`2), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(IntPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(Enumerable), Member = "Select", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(TablePair), typeof(TablePair)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(System.Collections.Generic.IEnumerable`1<MoonSharp.Interpreter.TablePair>), typeof(System.Func`2<MoonSharp.Interpreter.TablePair, MoonSharp.Interpreter.TablePair>)}, ReturnType = typeof(System.Collections.Generic.IEnumerable`1<MoonSharp.Interpreter.TablePair>))]
	[Token(Token = "0x600056E")]
	public IEnumerable<TablePair> get_Pairs() { }

	[Address(RVA = "0x312D90", Offset = "0x311F90", Length = "0x111")]
	[CalledBy(Type = typeof(SerializationExtensions), Member = "Serialize", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(bool), typeof(int)}, ReturnType = typeof(string))]
	[CalledBy(Type = typeof(EnumerableWrapper), Member = "ConvertTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[Calls(Type = typeof(Func`2), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(IntPtr)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(Enumerable), Member = "Select", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"TSource", "TResult"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"System.Collections.Generic.IEnumerable`1<TSource>", "System.Func`2<TSource, TResult>"}, ReturnType = "System.Collections.Generic.IEnumerable`1<TResult>")]
	[Token(Token = "0x6000570")]
	public IEnumerable<DynValue> get_Values() { }

	[Address(RVA = "0x3108F0", Offset = "0x30FAF0", Length = "0x28")]
	[CallerCount(Count = 0)]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000549")]
	private int GetIntegralKey(double d) { }

	[Address(RVA = "0x310920", Offset = "0x30FB20", Length = "0x1F5")]
	[CalledBy(Type = typeof(Table), Member = "NextKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(System.Nullable`1<MoonSharp.Interpreter.TablePair>))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LinkedListNode`1), Member = "get_Next", ReturnType = "System.Collections.Generic.LinkedListNode`1<T>")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Nullable`1), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000569")]
	private Nullable<TablePair> GetNextOf(LinkedListNode<TablePair> linkedListNode) { }

	[Address(RVA = "0x310FA0", Offset = "0x3101A0", Length = "0xE6")]
	[CalledBy(Type = typeof(Table), Member = "InitNextArrayKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Processor), Member = "ExecTblInitI", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(DynValue), Member = "ToScalar", ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(Table), Member = "InitNextArrayKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(bool)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x600056B")]
	internal void InitNextArrayKeys(DynValue val, bool lastpos) { }

	[Address(RVA = "0x311090", Offset = "0x310290", Length = "0x280")]
	[CalledBy(Type = typeof(Table), Member = "NextKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(System.Nullable`1<MoonSharp.Interpreter.TablePair>))]
	[CalledBy(Type = typeof(TableIteratorsModule), Member = "next", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = "System.Collections.Generic.LinkedListNode`1<TValue>")]
	[Calls(Type = typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(System.Collections.Generic.LinkedListNode`1<MoonSharp.Interpreter.TablePair>))]
	[Calls(Type = typeof(Table), Member = "GetNextOf", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(System.Collections.Generic.LinkedListNode`1<MoonSharp.Interpreter.TablePair>)}, ReturnType = typeof(System.Nullable`1<MoonSharp.Interpreter.TablePair>))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Table), Member = "NextKey", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(System.Nullable`1<MoonSharp.Interpreter.TablePair>))]
	[Calls(Type = typeof(Nullable`1), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000568")]
	public Nullable<TablePair> NextKey(DynValue v) { }

	[Address(RVA = "0x768CA0", Offset = "0x767EA0", Length = "0x7F")]
	[CalledBy(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(bool))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[DeduplicatedMethod]
	[Token(Token = "0x6000561")]
	private bool PerformTableRemove(LinkedListIndex<T, TablePair> listIndex, T key, bool isNumber) { }

	[Address(RVA = "0x769090", Offset = "0x768290", Length = "0x270")]
	[CalledBy(Type = typeof(Table), Member = "Append", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(DynValue)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = "System.Collections.Generic.LinkedListNode`1<TValue>")]
	[Calls(Type = typeof(DynValue), Member = "IsNilOrNan", ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey", "TValue"}, ReturnType = "TValue")]
	[Calls(Type = typeof(DynValue), Member = "IsNotNil", ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(DynValue), Member = "IsNil", ReturnType = typeof(bool))]
	[Calls(Type = typeof(Table), Member = "CollectDeadKeys", ReturnType = typeof(void))]
	[CallsDeduplicatedMethods(Count = 1)]
	[ContainsUnimplementedInstructions]
	[DeduplicatedMethod]
	[Token(Token = "0x6000550")]
	private void PerformTableSet(LinkedListIndex<T, TablePair> listIndex, T key, DynValue keyDynValue, DynValue value, bool isNumber, int appendKey) { }

	[Address(RVA = "0x3114C0", Offset = "0x3106C0", Length = "0x13B")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Table), Member = "ResolveMultipleKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(Object&)}, ReturnType = typeof(Table))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000560")]
	public DynValue RawGet(Object[] keys) { }

	[Address(RVA = "0x3113A0", Offset = "0x3105A0", Length = "0x119")]
	[CalledBy(Type = typeof(Table), Member = "get_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(object))]
	[CalledBy(Type = typeof(Table), Member = "ResolveMultipleKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(Object&)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Token(Token = "0x600055F")]
	public DynValue RawGet(object key) { }

	[Address(RVA = "0x311600", Offset = "0x310800", Length = "0xC0")]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(LinkedListIndex`2), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"TKey"}, ReturnType = "System.Collections.Generic.LinkedListNode`1<TValue>")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600055D")]
	public DynValue RawGet(int key) { }

	[Address(RVA = "0x3116D0", Offset = "0x3108D0", Length = "0xC2")]
	[CalledBy(Type = typeof(ReplInterpreterScriptLoader), Member = "ResolveModuleName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(Table)}, ReturnType = typeof(string))]
	[CalledBy(Type = typeof(Processor), Member = "Internal_InvokeUnaryMetaMethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(string), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(Processor), Member = "GetMetamethodRaw", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(string)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Processor), Member = "GetMetamethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(string)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Processor), Member = "GetBinaryMetamethod", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(DynValue), typeof(string)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(ScriptLoaderBase), Member = "ResolveModuleName", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(Table)}, ReturnType = typeof(string))]
	[CalledBy(Type = typeof(ModuleRegister), Member = "CreateModuleNamespace", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Type)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(CallbackArguments), Member = "AsStringUsingMeta", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(int), typeof(string)}, ReturnType = typeof(string))]
	[CalledBy(Type = typeof(MetaTableModule), Member = "getmetatable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 21)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(System.Collections.Generic.LinkedListNode`1<MoonSharp.Interpreter.TablePair>))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600055C")]
	public DynValue RawGet(string key) { }

	[Address(RVA = "0x3117A0", Offset = "0x3109A0", Length = "0x14E")]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), Member = "Find", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(System.Collections.Generic.LinkedListNode`1<MoonSharp.Interpreter.TablePair>))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600055E")]
	public DynValue RawGet(DynValue key) { }

	[Address(RVA = "0x311320", Offset = "0x310520", Length = "0x71")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x600055B")]
	private static DynValue RawGetValue(LinkedListNode<TablePair> linkedListNode) { }

	[Address(RVA = "0x311DB0", Offset = "0x310FB0", Length = "0x55")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "PerformTableRemove", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), typeof(object), typeof(bool)}, ReturnType = typeof(bool))]
	[Token(Token = "0x6000562")]
	public bool Remove(string key) { }

	[Address(RVA = "0x311AC0", Offset = "0x310CC0", Length = "0x54")]
	[CalledBy(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "PerformTableRemove", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<T, TablePair>", "T", typeof(bool)}, ReturnType = typeof(bool))]
	[Token(Token = "0x6000563")]
	public bool Remove(int key) { }

	[Address(RVA = "0x311CA0", Offset = "0x310EA0", Length = "0x10D")]
	[CalledBy(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(Table), Member = "CollectDeadKeys", ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Table), Member = "PerformTableRemove", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), typeof(object), typeof(bool)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000564")]
	public bool Remove(DynValue key) { }

	[Address(RVA = "0x311B20", Offset = "0x310D20", Length = "0x179")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(Table), Member = "PerformTableRemove", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<T, TablePair>", "T", typeof(bool)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Table), Member = "PerformTableRemove", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), typeof(object), typeof(bool)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[ContainsInvalidInstructions]
	[Token(Token = "0x6000565")]
	public bool Remove(object key) { }

	[Address(RVA = "0x3118F0", Offset = "0x310AF0", Length = "0x1C0")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Table), Member = "ResolveMultipleKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(Object&)}, ReturnType = typeof(Table))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(Table), Member = "PerformTableRemove", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<T, TablePair>", "T", typeof(bool)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(Table), Member = "PerformTableRemove", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), typeof(object), typeof(bool)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue)}, ReturnType = typeof(bool))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000566")]
	public bool Remove(Object[] keys) { }

	[Address(RVA = "0x311E10", Offset = "0x311010", Length = "0x16A")]
	[CalledBy(Type = typeof(Table), Member = "set_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(DynValue)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Table), Member = "Get", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "Remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[])}, ReturnType = typeof(bool))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(Table), Member = "RawGet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(DynValue), Member = "get_Table", ReturnType = typeof(Table))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA40")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA00")]
	[CallsDeduplicatedMethods(Count = 2)]
	[Token(Token = "0x600054E")]
	private Table ResolveMultipleKeys(Object[] keys, out object key) { }

	[Address(RVA = "0x3121B0", Offset = "0x3113B0", Length = "0x18B")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(Table), Member = "ResolveMultipleKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(Object&)}, ReturnType = typeof(Table))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ScriptRuntimeException), Member = "TableIndexIsNil", ReturnType = typeof(ScriptRuntimeException))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x6000555")]
	public void Set(Object[] keys, DynValue value) { }

	[Address(RVA = "0x312340", Offset = "0x311540", Length = "0x14E")]
	[CalledBy(Type = typeof(Table), Member = "set_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(object)}, ReturnType = typeof(void))]
	[CallerCount(Count = 1)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(ScriptRuntimeException), Member = "TableIndexIsNil", ReturnType = typeof(ScriptRuntimeException))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[ContainsInvalidInstructions]
	[Token(Token = "0x6000554")]
	public void Set(object key, DynValue value) { }

	[Address(RVA = "0x311F80", Offset = "0x311180", Length = "0x223")]
	[CalledBy(Type = typeof(MetaTableModule), Member = "rawset", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Processor), Member = "ExecIndexSet", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction), typeof(int)}, ReturnType = typeof(int))]
	[CalledBy(Type = typeof(Processor), Member = "ExecTblInitN", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Instruction)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertIDictionaryToTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(IDictionary)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(DynValue)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TableConstructor), Member = "Eval", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "set_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Table), Member = ".ctor", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(DynValue[])}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(DynValue), Member = "NewTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(DynValue[])}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(DynValue)}, ReturnType = typeof(void))]
	[CallerCount(Count = 10)]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(ScriptRuntimeException), Member = "TableIndexIsNaN", ReturnType = typeof(ScriptRuntimeException))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(Table), Member = "PerformTableSet", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), typeof(object), typeof(DynValue), typeof(DynValue), typeof(bool), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ScriptRuntimeException), Member = "TableIndexIsNil", ReturnType = typeof(ScriptRuntimeException))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(ScriptPrivateResource_Extension), Member = "CheckScriptOwnership", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IScriptPrivateResource), typeof(IScriptPrivateResource)}, ReturnType = typeof(void))]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000553")]
	public void Set(DynValue key, DynValue value) { }

	[Address(RVA = "0x312490", Offset = "0x311690", Length = "0xF4")]
	[CalledBy(Type = typeof(OverloadedMethodMemberDescriptor), Member = "PrepareForWiring", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TableModule_Globals), Member = "pack", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "remove", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "insert", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "sort", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(TableModule), Member = "pack", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(MethodMemberDescriptor), Member = "PrepareForWiring", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(GenericMethodMemberDescriptor), Member = "PrepareForWiring", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(TableConstructor), Member = "Eval", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(Table), Member = "InitNextArrayKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(DynValue)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(DynValue)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(Table), Member = "set_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(ArrayMemberDescriptor), Member = "PrepareForWiring", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table)}, ReturnType = typeof(void))]
	[CallerCount(Count = 16)]
	[Calls(Type = typeof(ScriptPrivateResource_Extension), Member = "CheckScriptOwnership", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IScriptPrivateResource), typeof(IScriptPrivateResource)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(Table), Member = "PerformTableSet", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {"MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<T, TablePair>", "T", typeof(DynValue), typeof(DynValue), typeof(bool), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(DynValue), Member = "NewNumber", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(double)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[ContainsUnimplementedInstructions]
	[Token(Token = "0x6000552")]
	public void Set(int key, DynValue value) { }

	[Address(RVA = "0x312590", Offset = "0x311790", Length = "0x11A")]
	[CallerCount(Count = 130)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED950")]
	[Calls(Type = typeof(ScriptPrivateResource_Extension), Member = "CheckScriptOwnership", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IScriptPrivateResource), typeof(IScriptPrivateResource)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(DynValue), Member = "NewString", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "PerformTableSet", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(MoonSharp.Interpreter.DataStructs.LinkedListIndex`2<System.Object, MoonSharp.Interpreter.TablePair>), typeof(object), typeof(DynValue), typeof(DynValue), typeof(bool), typeof(int)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ScriptRuntimeException), Member = "TableIndexIsNil", ReturnType = typeof(ScriptRuntimeException))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Token(Token = "0x6000551")]
	public void Set(string key, DynValue value) { }

	[Address(RVA = "0x312EB0", Offset = "0x3120B0", Length = "0x1DD")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "ResolveMultipleKeys", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Object[]), typeof(Object&)}, ReturnType = typeof(Table))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(DynValue), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_object_unbox")]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(int), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(DynValue)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(ScriptRuntimeException), Member = "TableIndexIsNil", ReturnType = typeof(ScriptRuntimeException))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE830")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA10")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED970")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Token(Token = "0x600054B")]
	public void set_Item(Object[] keys, object value) { }

	[Address(RVA = "0x313090", Offset = "0x312290", Length = "0x85")]
	[CalledBy(Type = "Polytoria.Datamodel.BaseScript", Member = "set_Item", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(string), typeof(object)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Services.ScriptService+<RunScriptInstance>d__13", Member = "MoveNext", ReturnType = typeof(bool))]
	[CalledBy(Type = typeof(TableConversions), Member = "ConvertIListToTable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(IList)}, ReturnType = typeof(Table))]
	[CalledBy(Type = typeof(LoadModule), Member = "MoonSharpInit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Table)}, ReturnType = typeof(void))]
	[CallerCount(Count = 47)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "il2cpp_runtime_class_init")]
	[Calls(Type = typeof(ClrToScriptConversions), Member = "ObjectToDynValue", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Script), typeof(object)}, ReturnType = typeof(DynValue))]
	[Calls(Type = typeof(Table), Member = "Set", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object), typeof(DynValue)}, ReturnType = typeof(void))]
	[Token(Token = "0x600054D")]
	public void set_Item(object key, object value) { }

	[Address(RVA = "0x313120", Offset = "0x312320", Length = "0x36")]
	[CalledBy(Type = typeof(DebugModule), Member = "setmetatable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CalledBy(Type = typeof(IoModule), Member = "MoonSharpInit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Table), typeof(Table)}, ReturnType = typeof(void))]
	[CalledBy(Type = typeof(MetaTableModule), Member = "setmetatable", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(ScriptExecutionContext), typeof(CallbackArguments)}, ReturnType = typeof(DynValue))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(ScriptPrivateResource_Extension), Member = "CheckScriptOwnership", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IScriptPrivateResource), typeof(IScriptPrivateResource)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801ED930")]
	[Token(Token = "0x600056D")]
	public void set_MetaTable(Table value) { }

}

