namespace UnityEngine;

[NativeHeader("Modules/Physics/Collider.h")]
[Token(Token = "0x2000012")]
public class Collider : Component
{

	[Token(Token = "0x1700001A")]
	public Rigidbody attachedRigidbody
	{
		[Address(RVA = "0x19E5350", Offset = "0x19E4550", Length = "0x90")]
		[CallerCount(Count = 0)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = "UnityEngine.Bindings.Unmarshal", Member = "UnmarshalUnityObject", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IntPtr)}, ReturnType = "T")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsUnknownMethods(Count = 1)]
		[NativeMethod("GetRigidbody")]
		[Token(Token = "0x600004F")]
		 get { } //Length: 144
	}

	[Token(Token = "0x1700001C")]
	public Bounds bounds
	{
		[Address(RVA = "0x19E5440", Offset = "0x19E4640", Length = "0x94")]
		[CalledBy(Type = "Mirror.HistoryCollider", Member = "CaptureBounds", ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictedRigidbody", Member = "Awake", ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.LagCompensator", Member = "Capture", ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.HistoryCollider", Member = "OnDrawGizmos", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Sit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.Seat"}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Controllers.CreatorController", Member = "GroupSelection", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "DoFootstep", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Move", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(float)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.NPC", Member = "IsGrounded", ReturnType = typeof(bool))]
		[CalledBy(Type = "Polytoria.Datamodel.Instance", Member = "GetBounds", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.BoundsCalculationMethod"}, ReturnType = typeof(Bounds))]
		[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "IsGrounded", ReturnType = typeof(bool))]
		[CallerCount(Count = 20)]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x6000053")]
		 get { } //Length: 148
	}

	[Token(Token = "0x17000019")]
	public bool enabled
	{
		[Address(RVA = "0x19E5520", Offset = "0x19E4720", Length = "0x76")]
		[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessManager", Member = "GetActiveVolumes", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.Rendering.PostProcessing.PostProcessLayer", "System.Collections.Generic.List`1<PostProcessVolume>", typeof(bool), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessManager", Member = "UpdateSettings", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.Rendering.PostProcessing.PostProcessLayer", typeof(Camera)}, ReturnType = typeof(void))]
		[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessVolume", Member = "OnDrawGizmos", ReturnType = typeof(void))]
		[CallerCount(Count = 3)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x600004D")]
		 get { } //Length: 118
		[Address(RVA = "0x19E5870", Offset = "0x19E4A70", Length = "0x86")]
		[CallerCount(Count = 32)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x600004E")]
		 set { } //Length: 134
	}

	[Token(Token = "0x1700001B")]
	public bool isTrigger
	{
		[Address(RVA = "0x19E55E0", Offset = "0x19E47E0", Length = "0x76")]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.NPC+<>c", Member = "<IsGrounded>b__110_0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Collider)}, ReturnType = typeof(bool))]
		[CalledBy(Type = "Polytoria.Datamodel.Player+<>c", Member = "<DoFootstep>b__211_0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Collider)}, ReturnType = typeof(bool))]
		[CalledBy(Type = "Polytoria.Datamodel.Player+<>c", Member = "<IsGrounded>b__225_0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Collider)}, ReturnType = typeof(bool))]
		[CalledBy(Type = "Mirror.HistoryCollider", Member = "Awake", ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CallerCount(Count = 9)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x6000050")]
		 get { } //Length: 118
		[Address(RVA = "0x19E5950", Offset = "0x19E4B50", Length = "0x86")]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_CanCollide", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Shape", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.PartShape"}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.MeshPart", Member = "OnShow", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.MeshPart", Member = "UpdateColliders", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.MeshPart", Member = "set_CanCollide", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "UnityEngine.UIElements.UIDocument", Member = "UpdateWorldSpaceCollider", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.UIElements.ColliderUpdateMode"}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "OnShow", ReturnType = typeof(void))]
		[CallerCount(Count = 13)]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x6000051")]
		 set { } //Length: 134
	}

	[Token(Token = "0x1700001E")]
	public PhysicsMaterial material
	{
		[Address(RVA = "0x19E56A0", Offset = "0x19E48A0", Length = "0x90")]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CallerCount(Count = 5)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = "UnityEngine.Bindings.Unmarshal", Member = "UnmarshalUnityObject", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IntPtr)}, ReturnType = "T")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsUnknownMethods(Count = 1)]
		[NativeMethod("GetClonedMaterial")]
		[Token(Token = "0x6000056")]
		 get { } //Length: 144
		[Address(RVA = "0x19E5A30", Offset = "0x19E4C30", Length = "0xBA")]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "FixedUpdate", ReturnType = typeof(void))]
		[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Start", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.NPC", Member = "Jump", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.NPC", Member = "Start", ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Update", ReturnType = typeof(void))]
		[CallerCount(Count = 10)]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
		[CallsUnknownMethods(Count = 1)]
		[NativeMethod("SetMaterial")]
		[Token(Token = "0x6000057")]
		 set { } //Length: 186
	}

	[NativeMethod("Material")]
	[Token(Token = "0x1700001D")]
	public PhysicsMaterial sharedMaterial
	{
		[Address(RVA = "0x19E5780", Offset = "0x19E4980", Length = "0x90")]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_BounceCombine", ReturnType = typeof(PhysicsMaterialCombine))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "CopyProperties", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.Instance"}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_BounceCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_FrictionCombine", ReturnType = typeof(PhysicsMaterialCombine))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Friction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_FrictionCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Bounciness", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_Bounciness", ReturnType = typeof(float))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Shape", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.PartShape"}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_Friction", ReturnType = typeof(float))]
		[CallerCount(Count = 13)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = "UnityEngine.Bindings.Unmarshal", Member = "UnmarshalUnityObject", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IntPtr)}, ReturnType = "T")]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x6000054")]
		 get { } //Length: 144
		[Address(RVA = "0x19E5B40", Offset = "0x19E4D40", Length = "0xBA")]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Shape", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.PartShape"}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Bounciness", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Friction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_FrictionCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
		[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_BounceCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
		[CallerCount(Count = 5)]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
		[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
		[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
		[CallsUnknownMethods(Count = 1)]
		[Token(Token = "0x6000055")]
		 set { } //Length: 186
	}

	[Address(RVA = "0x2C7050", Offset = "0x2C6250", Length = "0x7")]
	[CallerCount(Count = 60)]
	[CallsDeduplicatedMethods(Count = 1)]
	[DeduplicatedMethod]
	[Token(Token = "0x600005A")]
	public Collider() { }

	[Address(RVA = "0x19E5000", Offset = "0x19E4200", Length = "0xA0")]
	[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessManager", Member = "GetActiveVolumes", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.Rendering.PostProcessing.PostProcessLayer", "System.Collections.Generic.List`1<PostProcessVolume>", typeof(bool), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessManager", Member = "UpdateSettings", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.Rendering.PostProcessing.PostProcessLayer", typeof(Camera)}, ReturnType = typeof(void))]
	[CallerCount(Count = 2)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000052")]
	public Vector3 ClosestPoint(Vector3 position) { }

	[Address(RVA = "0x19E4FA0", Offset = "0x19E41A0", Length = "0x52")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000060")]
	private static void ClosestPoint_Injected(IntPtr _unity_self, in Vector3 position, out Vector3 ret) { }

	[Address(RVA = "0x19E5350", Offset = "0x19E4550", Length = "0x90")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = "UnityEngine.Bindings.Unmarshal", Member = "UnmarshalUnityObject", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IntPtr)}, ReturnType = "T")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[NativeMethod("GetRigidbody")]
	[Token(Token = "0x600004F")]
	public Rigidbody get_attachedRigidbody() { }

	[Address(RVA = "0x19E5310", Offset = "0x19E4510", Length = "0x33")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x600005D")]
	private static IntPtr get_attachedRigidbody_Injected(IntPtr _unity_self) { }

	[Address(RVA = "0x19E5440", Offset = "0x19E4640", Length = "0x94")]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "IsGrounded", ReturnType = typeof(bool))]
	[CalledBy(Type = "Polytoria.Datamodel.Instance", Member = "GetBounds", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.BoundsCalculationMethod"}, ReturnType = typeof(Bounds))]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Move", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float), typeof(float)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "DoFootstep", ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Controllers.CreatorController", Member = "GroupSelection", ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.NPC", Member = "IsGrounded", ReturnType = typeof(bool))]
	[CalledBy(Type = "Mirror.HistoryCollider", Member = "OnDrawGizmos", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.LagCompensator", Member = "Capture", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictedRigidbody", Member = "Awake", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.HistoryCollider", Member = "CaptureBounds", ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Sit", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.Seat"}, ReturnType = typeof(void))]
	[CallerCount(Count = 20)]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000053")]
	public Bounds get_bounds() { }

	[Address(RVA = "0x19E53F0", Offset = "0x19E45F0", Length = "0x42")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000061")]
	private static void get_bounds_Injected(IntPtr _unity_self, out Bounds ret) { }

	[Address(RVA = "0x19E5520", Offset = "0x19E4720", Length = "0x76")]
	[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessManager", Member = "GetActiveVolumes", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.Rendering.PostProcessing.PostProcessLayer", "System.Collections.Generic.List`1<PostProcessVolume>", typeof(bool), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessManager", Member = "UpdateSettings", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.Rendering.PostProcessing.PostProcessLayer", typeof(Camera)}, ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.Rendering.PostProcessing.PostProcessVolume", Member = "OnDrawGizmos", ReturnType = typeof(void))]
	[CallerCount(Count = 3)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x600004D")]
	public bool get_enabled() { }

	[Address(RVA = "0x19E54E0", Offset = "0x19E46E0", Length = "0x33")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x600005B")]
	private static bool get_enabled_Injected(IntPtr _unity_self) { }

	[Address(RVA = "0x19E55E0", Offset = "0x19E47E0", Length = "0x76")]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.HistoryCollider", Member = "Awake", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Player+<>c", Member = "<DoFootstep>b__211_0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Collider)}, ReturnType = typeof(bool))]
	[CalledBy(Type = "Polytoria.Datamodel.NPC+<>c", Member = "<IsGrounded>b__110_0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Collider)}, ReturnType = typeof(bool))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Player+<>c", Member = "<IsGrounded>b__225_0", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Collider)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 9)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000050")]
	public bool get_isTrigger() { }

	[Address(RVA = "0x19E55A0", Offset = "0x19E47A0", Length = "0x33")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x600005E")]
	private static bool get_isTrigger_Injected(IntPtr _unity_self) { }

	[Address(RVA = "0x19E56A0", Offset = "0x19E48A0", Length = "0x90")]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = "UnityEngine.Bindings.Unmarshal", Member = "UnmarshalUnityObject", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IntPtr)}, ReturnType = "T")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[NativeMethod("GetClonedMaterial")]
	[Token(Token = "0x6000056")]
	public PhysicsMaterial get_material() { }

	[Address(RVA = "0x19E5660", Offset = "0x19E4860", Length = "0x33")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000064")]
	private static IntPtr get_material_Injected(IntPtr _unity_self) { }

	[Address(RVA = "0x19E5780", Offset = "0x19E4980", Length = "0x90")]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_Friction", ReturnType = typeof(float))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_Bounciness", ReturnType = typeof(float))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Bounciness", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_FrictionCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Shape", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.PartShape"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_FrictionCombine", ReturnType = typeof(PhysicsMaterialCombine))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_BounceCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "CopyProperties", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.Instance"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "get_BounceCombine", ReturnType = typeof(PhysicsMaterialCombine))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Friction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
	[CallerCount(Count = 13)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = "UnityEngine.Bindings.Unmarshal", Member = "UnmarshalUnityObject", MemberTypeParameters = new IL2CPP_TYPE_OBJECT[] {"T"}, MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(IntPtr)}, ReturnType = "T")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000054")]
	public PhysicsMaterial get_sharedMaterial() { }

	[Address(RVA = "0x19E5740", Offset = "0x19E4940", Length = "0x33")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000062")]
	private static IntPtr get_sharedMaterial_Injected(IntPtr _unity_self) { }

	[Address(RVA = "0x19E51F0", Offset = "0x19E43F0", Length = "0x118")]
	[CalledBy(Type = "RLD.RTScene", Member = "RaycastMeshObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Ray), typeof(GameObject)}, ReturnType = "RLD.GameObjectRayHit")]
	[CalledBy(Type = "RLD.SceneTree", Member = "RaycastMeshObject", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Ray), typeof(GameObject)}, ReturnType = "RLD.GameObjectRayHit")]
	[CalledBy(Type = "Polytoria.Datamodel.NPC", Member = "ResolveStepUp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector3&), typeof(ContactPoint), typeof(ContactPoint)}, ReturnType = typeof(bool))]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "ResolveStepUp", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(Vector3&), typeof(ContactPoint), typeof(ContactPoint)}, ReturnType = typeof(bool))]
	[CallerCount(Count = 4)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000059")]
	public bool Raycast(Ray ray, out RaycastHit hitInfo, float maxDistance) { }

	[Address(RVA = "0x19E5120", Offset = "0x19E4320", Length = "0xC2")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000058")]
	private RaycastHit Raycast(Ray ray, float maxDistance, ref bool hasHit) { }

	[Address(RVA = "0x19E50B0", Offset = "0x19E42B0", Length = "0x62")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000066")]
	private static void Raycast_Injected(IntPtr _unity_self, in Ray ray, float maxDistance, ref bool hasHit, out RaycastHit ret) { }

	[Address(RVA = "0x19E5870", Offset = "0x19E4A70", Length = "0x86")]
	[CallerCount(Count = 32)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x600004E")]
	public void set_enabled(bool value) { }

	[Address(RVA = "0x19E5820", Offset = "0x19E4A20", Length = "0x42")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x600005C")]
	private static void set_enabled_Injected(IntPtr _unity_self, bool value) { }

	[Address(RVA = "0x19E5950", Offset = "0x19E4B50", Length = "0x86")]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "OnShow", ReturnType = typeof(void))]
	[CalledBy(Type = "UnityEngine.UIElements.UIDocument", Member = "UpdateWorldSpaceCollider", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"UnityEngine.UIElements.ColliderUpdateMode"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.MeshPart", Member = "set_CanCollide", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.MeshPart", Member = "OnShow", ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Shape", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.PartShape"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.MeshPart", Member = "UpdateColliders", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_CanCollide", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(bool)}, ReturnType = typeof(void))]
	[CallerCount(Count = 13)]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000051")]
	public void set_isTrigger(bool value) { }

	[Address(RVA = "0x19E5900", Offset = "0x19E4B00", Length = "0x42")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x600005F")]
	private static void set_isTrigger_Injected(IntPtr _unity_self, bool value) { }

	[Address(RVA = "0x19E5A30", Offset = "0x19E4C30", Length = "0xBA")]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Update", ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.NPC", Member = "Jump", ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "Start", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveBoxColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.NPC", Member = "Start", ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveCapsuleColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveMeshColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveAllColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Mirror.PredictionUtils", Member = "MoveSphereColliders", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(GameObject), typeof(GameObject), typeof(bool)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Player", Member = "FixedUpdate", ReturnType = typeof(void))]
	[CallerCount(Count = 10)]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
	[CallsUnknownMethods(Count = 1)]
	[NativeMethod("SetMaterial")]
	[Token(Token = "0x6000057")]
	public void set_material(PhysicsMaterial value) { }

	[Address(RVA = "0x19E59E0", Offset = "0x19E4BE0", Length = "0x42")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000065")]
	private static void set_material_Injected(IntPtr _unity_self, IntPtr value) { }

	[Address(RVA = "0x19E5B40", Offset = "0x19E4D40", Length = "0xBA")]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Shape", MemberParameters = new IL2CPP_TYPE_OBJECT[] {"Polytoria.Datamodel.PartShape"}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Bounciness", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_Friction", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(float)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_FrictionCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
	[CalledBy(Type = "Polytoria.Datamodel.Part", Member = "set_BounceCombine", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(PhysicsMaterialCombine)}, ReturnType = typeof(void))]
	[CallerCount(Count = 5)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EE810")]
	[Calls(Type = "UnityEngine.Bindings.ThrowHelper", Member = "ThrowNullReferenceException", MemberParameters = new IL2CPP_TYPE_OBJECT[] {typeof(object)}, ReturnType = typeof(void))]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801F7350")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEA50")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000055")]
	public void set_sharedMaterial(PhysicsMaterial value) { }

	[Address(RVA = "0x19E5AF0", Offset = "0x19E4CF0", Length = "0x42")]
	[CallerCount(Count = 0)]
	[Calls(Type = typeof(CppNativeMethods), Member = "NativeMethod_0x1801EEAB0")]
	[CallsUnknownMethods(Count = 1)]
	[Token(Token = "0x6000063")]
	private static void set_sharedMaterial_Injected(IntPtr _unity_self, IntPtr value) { }

}

